// Auto-generated by scripts/generate-licenses.mjs
// Do not edit directly. Update the generator if changes are required.

export interface LicenseRecord {
  id: number;
  slug: string;
  companyName: string;
  licenseNumber: string;
  issueDate: string;
  expiryDate: string;
  status: string;
  registeredAddress: string;
  contactEmail: string;
  contactPhone: string;
  businessCategory: string;
  complianceNotes: string;
  description: string;
  keyPersons: { name: string; role: string }[];
}

export const licenses = [
  {
    "id": 1,
    "slug": "atlantic-bridge-advisors",
    "companyName": "Atlantic Bridge Advisors",
    "licenseNumber": "CV-BOA-2014-0001",
    "issueDate": "2014-01-01",
    "expiryDate": "N/A",
    "status": "Active",
    "registeredAddress": "12 Povoação Velha Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@atlantic-bridge-advisors.cv",
    "contactPhone": "+238 59000 200",
    "businessCategory": "Retail FX Brokerage",
    "complianceNotes": "Maintains quarterly compliance updates with the Boa Vista Financial Authority.",
    "description": "Founded in 2014, Atlantic Bridge Advisors delivers currency execution and settlement solutions to the Cape Verdean hospitality and tourism sector.",
    "keyPersons": [
      {
        "name": "Ana Almeida",
        "role": "Managing Director"
      },
      {
        "name": "Daniel Fernandes",
        "role": "Chief Compliance Officer"
      }
    ]
  },
  {
    "id": 2,
    "slug": "azure-bridge-holdings",
    "companyName": "Azure Bridge Holdings",
    "licenseNumber": "CV-BOA-2015-0002",
    "issueDate": "2015-04-08",
    "expiryDate": "2020-04-08",
    "status": "Active",
    "registeredAddress": "13 Rabil Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@azure-bridge-holdings.cv",
    "contactPhone": "+238 59013 207",
    "businessCategory": "Institutional FX Brokerage",
    "complianceNotes": "Underwent enhanced due diligence during the most recent supervisory cycle.",
    "description": "Founded in 2015, Azure Bridge Holdings supports regional exporters with hedging strategies against Euro and USD volatility.",
    "keyPersons": [
      {
        "name": "Bruno Cardoso",
        "role": "Chief Compliance Officer"
      },
      {
        "name": "Elisa Henriques",
        "role": "Head of Trading"
      },
      {
        "name": "Igor Pereira",
        "role": "Risk Management Lead"
      }
    ]
  },
  {
    "id": 3,
    "slug": "beacon-bridge-partners",
    "companyName": "Beacon Bridge Partners",
    "licenseNumber": "CV-BOA-2016-0003",
    "issueDate": "2016-07-15",
    "expiryDate": "2021-07-15",
    "status": "Active",
    "registeredAddress": "14 Sal Rei Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@beacon-bridge-partners.cv",
    "contactPhone": "+238 59026 214",
    "businessCategory": "Multi-Asset Dealing Desk",
    "complianceNotes": "Submitted revised capital adequacy statement in the last reporting period.",
    "description": "Founded in 2016, Beacon Bridge Partners specialises in low-latency order routing for diaspora remittance channels.",
    "keyPersons": [
      {
        "name": "Carla Esteves",
        "role": "Head of Trading"
      },
      {
        "name": "Fabio Macedo",
        "role": "Risk Management Lead"
      }
    ]
  },
  {
    "id": 4,
    "slug": "blue-bridge-ventures",
    "companyName": "Blue Bridge Ventures",
    "licenseNumber": "CV-BOA-2017-0004",
    "issueDate": "2017-10-22",
    "expiryDate": "2022-10-22",
    "status": "Active",
    "registeredAddress": "15 Bofareira Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@blue-bridge-ventures.cv",
    "contactPhone": "+238 59039 221",
    "businessCategory": "FX Liquidity Provision",
    "complianceNotes": "Implements mandatory client asset segregation with monthly reconciliations.",
    "description": "Founded in 2017, Blue Bridge Ventures partners with local banks to provide treasury outsourcing and liquidity management.",
    "keyPersons": [
      {
        "name": "Daniel Gomes",
        "role": "Risk Management Lead"
      },
      {
        "name": "Helena Oliveira",
        "role": "Operations Supervisor"
      },
      {
        "name": "Luis Tavares",
        "role": "Client Relations Principal"
      }
    ]
  },
  {
    "id": 5,
    "slug": "coral-bridge-consulting",
    "companyName": "Coral Bridge Consulting",
    "licenseNumber": "CV-BOA-2018-0005",
    "issueDate": "2018-01-01",
    "expiryDate": "2023-01-01",
    "status": "Under Review",
    "registeredAddress": "16 Estância de Baixo Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@coral-bridge-consulting.cv",
    "contactPhone": "+238 59052 228",
    "businessCategory": "Commodities Brokerage",
    "complianceNotes": "Participates in cross-border information sharing with Lusophone regulators.",
    "description": "Founded in 2018, Coral Bridge Consulting offers portfolio diversification tools for high-net-worth investors across West Africa.",
    "keyPersons": [
      {
        "name": "Elisa Lima",
        "role": "Operations Supervisor"
      },
      {
        "name": "Igor Quintino",
        "role": "Client Relations Principal"
      }
    ]
  },
  {
    "id": 6,
    "slug": "emerald-bridge-markets",
    "companyName": "Emerald Bridge Markets",
    "licenseNumber": "CV-BOA-2019-0006",
    "issueDate": "2019-04-08",
    "expiryDate": "2024-04-08",
    "status": "Suspended",
    "registeredAddress": "17 Povoação Velha Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@emerald-bridge-markets.cv",
    "contactPhone": "+238 59065 235",
    "businessCategory": "Derivatives Advisory",
    "complianceNotes": "Filed updated disaster recovery plan incorporating offshore redundancy.",
    "description": "Founded in 2019, Emerald Bridge Markets focuses on sustainable finance instruments linked to island infrastructure projects.",
    "keyPersons": [
      {
        "name": "Fabio Neves",
        "role": "Client Relations Principal"
      },
      {
        "name": "Joana Silva",
        "role": "Managing Director"
      },
      {
        "name": "Nuno Almeida",
        "role": "Chief Compliance Officer"
      }
    ]
  },
  {
    "id": 7,
    "slug": "harbor-bridge-trust",
    "companyName": "Harbor Bridge Trust",
    "licenseNumber": "CV-BOA-2020-0007",
    "issueDate": "2020-07-15",
    "expiryDate": "2025-07-15",
    "status": "Lapsed",
    "registeredAddress": "18 Rabil Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@harbor-bridge-trust.cv",
    "contactPhone": "+238 59078 242",
    "businessCategory": "Wealth Management Services",
    "complianceNotes": "Completed independent AML/CTF audit with satisfactory findings.",
    "description": "Founded in 2020, Harbor Bridge Trust implements disciplined risk management tailored to maritime shipping clients.",
    "keyPersons": [
      {
        "name": "Helena Pereira",
        "role": "Managing Director"
      },
      {
        "name": "Luis Vidal",
        "role": "Chief Compliance Officer"
      }
    ]
  },
  {
    "id": 8,
    "slug": "mariner-bridge-associates",
    "companyName": "Mariner Bridge Associates",
    "licenseNumber": "CV-BOA-2021-0008",
    "issueDate": "2021-10-22",
    "expiryDate": "N/A",
    "status": "Active",
    "registeredAddress": "19 Sal Rei Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@mariner-bridge-associates.cv",
    "contactPhone": "+238 59091 249",
    "businessCategory": "Payment and Remittance Services",
    "complianceNotes": "Subject to annual prudential assessment focusing on liquidity buffers.",
    "description": "Founded in 2021, Mariner Bridge Associates provides onboarding support for fintech entrants expanding into Lusophone markets.",
    "keyPersons": [
      {
        "name": "Igor Ramos",
        "role": "Chief Compliance Officer"
      },
      {
        "name": "Marta Zamora",
        "role": "Head of Trading"
      },
      {
        "name": "Paulo Esteves",
        "role": "Risk Management Lead"
      }
    ]
  },
  {
    "id": 9,
    "slug": "palm-bridge-investments",
    "companyName": "Palm Bridge Investments",
    "licenseNumber": "CV-BOA-2022-0009",
    "issueDate": "2022-01-01",
    "expiryDate": "2027-01-01",
    "status": "Active",
    "registeredAddress": "20 Bofareira Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@palm-bridge-investments.cv",
    "contactPhone": "+238 59104 256",
    "businessCategory": "Treasury Outsourcing",
    "complianceNotes": "Maintains bilingual client disclosures in Portuguese and English.",
    "description": "Founded in 2022, Palm Bridge Investments operates bespoke FX solutions for renewable energy initiatives throughout Boa Vista.",
    "keyPersons": [
      {
        "name": "Joana Tavares",
        "role": "Head of Trading"
      },
      {
        "name": "Nuno Barbosa",
        "role": "Risk Management Lead"
      }
    ]
  },
  {
    "id": 10,
    "slug": "sand-bridge-services",
    "companyName": "Sand Bridge Services",
    "licenseNumber": "CV-BOA-2023-0010",
    "issueDate": "2023-04-08",
    "expiryDate": "2028-04-08",
    "status": "Active",
    "registeredAddress": "21 Estância de Baixo Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@sand-bridge-services.cv",
    "contactPhone": "+238 59117 263",
    "businessCategory": "Corporate FX Risk Advisory",
    "complianceNotes": "Operates under conditional approval pending technology platform migration.",
    "description": "Founded in 2023, Sand Bridge Services maintains correspondent networks facilitating cross-border commodity trades.",
    "keyPersons": [
      {
        "name": "Luis Xavier",
        "role": "Risk Management Lead"
      },
      {
        "name": "Olivia Delgado",
        "role": "Operations Supervisor"
      },
      {
        "name": "Sergio Lima",
        "role": "Client Relations Principal"
      }
    ]
  },
  {
    "id": 11,
    "slug": "atlantic-capital-advisors",
    "companyName": "Atlantic Capital Advisors",
    "licenseNumber": "CV-BOA-2014-0011",
    "issueDate": "2014-07-15",
    "expiryDate": "2019-07-15",
    "status": "Active",
    "registeredAddress": "22 Povoação Velha Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@atlantic-capital-advisors.cv",
    "contactPhone": "+238 59130 270",
    "businessCategory": "Retail FX Brokerage",
    "complianceNotes": "Maintains quarterly compliance updates with the Boa Vista Financial Authority.",
    "description": "Founded in 2014, Atlantic Capital Advisors delivers currency execution and settlement solutions to the Cape Verdean hospitality and tourism sector.",
    "keyPersons": [
      {
        "name": "Marta Almeida",
        "role": "Operations Supervisor"
      },
      {
        "name": "Paulo Fernandes",
        "role": "Client Relations Principal"
      }
    ]
  },
  {
    "id": 12,
    "slug": "azure-capital-holdings",
    "companyName": "Azure Capital Holdings",
    "licenseNumber": "CV-BOA-2015-0012",
    "issueDate": "2015-10-22",
    "expiryDate": "2020-10-22",
    "status": "Under Review",
    "registeredAddress": "23 Rabil Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@azure-capital-holdings.cv",
    "contactPhone": "+238 59143 277",
    "businessCategory": "Institutional FX Brokerage",
    "complianceNotes": "Underwent enhanced due diligence during the most recent supervisory cycle.",
    "description": "Founded in 2015, Azure Capital Holdings supports regional exporters with hedging strategies against Euro and USD volatility.",
    "keyPersons": [
      {
        "name": "Nuno Cardoso",
        "role": "Client Relations Principal"
      },
      {
        "name": "Rita Henriques",
        "role": "Managing Director"
      },
      {
        "name": "Vasco Pereira",
        "role": "Chief Compliance Officer"
      }
    ]
  },
  {
    "id": 13,
    "slug": "beacon-capital-partners",
    "companyName": "Beacon Capital Partners",
    "licenseNumber": "CV-BOA-2016-0013",
    "issueDate": "2016-01-01",
    "expiryDate": "2021-01-01",
    "status": "Suspended",
    "registeredAddress": "24 Sal Rei Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@beacon-capital-partners.cv",
    "contactPhone": "+238 59156 284",
    "businessCategory": "Multi-Asset Dealing Desk",
    "complianceNotes": "Submitted revised capital adequacy statement in the last reporting period.",
    "description": "Founded in 2016, Beacon Capital Partners specialises in low-latency order routing for diaspora remittance channels.",
    "keyPersons": [
      {
        "name": "Olivia Esteves",
        "role": "Managing Director"
      },
      {
        "name": "Sergio Macedo",
        "role": "Chief Compliance Officer"
      }
    ]
  },
  {
    "id": 14,
    "slug": "blue-capital-ventures",
    "companyName": "Blue Capital Ventures",
    "licenseNumber": "CV-BOA-2017-0014",
    "issueDate": "2017-04-08",
    "expiryDate": "2022-04-08",
    "status": "Lapsed",
    "registeredAddress": "25 Bofareira Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@blue-capital-ventures.cv",
    "contactPhone": "+238 59169 291",
    "businessCategory": "FX Liquidity Provision",
    "complianceNotes": "Implements mandatory client asset segregation with monthly reconciliations.",
    "description": "Founded in 2017, Blue Capital Ventures partners with local banks to provide treasury outsourcing and liquidity management.",
    "keyPersons": [
      {
        "name": "Paulo Gomes",
        "role": "Chief Compliance Officer"
      },
      {
        "name": "Teresa Oliveira",
        "role": "Head of Trading"
      },
      {
        "name": "Yuri Tavares",
        "role": "Risk Management Lead"
      }
    ]
  },
  {
    "id": 15,
    "slug": "coral-capital-consulting",
    "companyName": "Coral Capital Consulting",
    "licenseNumber": "CV-BOA-2018-0015",
    "issueDate": "2018-07-15",
    "expiryDate": "N/A",
    "status": "Active",
    "registeredAddress": "26 Estância de Baixo Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@coral-capital-consulting.cv",
    "contactPhone": "+238 59182 298",
    "businessCategory": "Commodities Brokerage",
    "complianceNotes": "Participates in cross-border information sharing with Lusophone regulators.",
    "description": "Founded in 2018, Coral Capital Consulting offers portfolio diversification tools for high-net-worth investors across West Africa.",
    "keyPersons": [
      {
        "name": "Rita Lima",
        "role": "Head of Trading"
      },
      {
        "name": "Vasco Quintino",
        "role": "Risk Management Lead"
      }
    ]
  },
  {
    "id": 16,
    "slug": "emerald-capital-markets",
    "companyName": "Emerald Capital Markets",
    "licenseNumber": "CV-BOA-2019-0016",
    "issueDate": "2019-10-22",
    "expiryDate": "2024-10-22",
    "status": "Active",
    "registeredAddress": "27 Povoação Velha Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@emerald-capital-markets.cv",
    "contactPhone": "+238 59195 305",
    "businessCategory": "Derivatives Advisory",
    "complianceNotes": "Filed updated disaster recovery plan incorporating offshore redundancy.",
    "description": "Founded in 2019, Emerald Capital Markets focuses on sustainable finance instruments linked to island infrastructure projects.",
    "keyPersons": [
      {
        "name": "Sergio Neves",
        "role": "Risk Management Lead"
      },
      {
        "name": "Wilma Silva",
        "role": "Operations Supervisor"
      },
      {
        "name": "Bruno Almeida",
        "role": "Client Relations Principal"
      }
    ]
  },
  {
    "id": 17,
    "slug": "harbor-capital-trust",
    "companyName": "Harbor Capital Trust",
    "licenseNumber": "CV-BOA-2020-0017",
    "issueDate": "2020-01-01",
    "expiryDate": "2025-01-01",
    "status": "Active",
    "registeredAddress": "28 Rabil Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@harbor-capital-trust.cv",
    "contactPhone": "+238 59208 312",
    "businessCategory": "Wealth Management Services",
    "complianceNotes": "Completed independent AML/CTF audit with satisfactory findings.",
    "description": "Founded in 2020, Harbor Capital Trust implements disciplined risk management tailored to maritime shipping clients.",
    "keyPersons": [
      {
        "name": "Teresa Pereira",
        "role": "Operations Supervisor"
      },
      {
        "name": "Yuri Vidal",
        "role": "Client Relations Principal"
      }
    ]
  },
  {
    "id": 18,
    "slug": "mariner-capital-associates",
    "companyName": "Mariner Capital Associates",
    "licenseNumber": "CV-BOA-2021-0018",
    "issueDate": "2021-04-08",
    "expiryDate": "2026-04-08",
    "status": "Active",
    "registeredAddress": "29 Sal Rei Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@mariner-capital-associates.cv",
    "contactPhone": "+238 59221 319",
    "businessCategory": "Payment and Remittance Services",
    "complianceNotes": "Subject to annual prudential assessment focusing on liquidity buffers.",
    "description": "Founded in 2021, Mariner Capital Associates provides onboarding support for fintech entrants expanding into Lusophone markets.",
    "keyPersons": [
      {
        "name": "Vasco Ramos",
        "role": "Client Relations Principal"
      },
      {
        "name": "Ana Zamora",
        "role": "Managing Director"
      },
      {
        "name": "Daniel Esteves",
        "role": "Chief Compliance Officer"
      }
    ]
  },
  {
    "id": 19,
    "slug": "palm-capital-investments",
    "companyName": "Palm Capital Investments",
    "licenseNumber": "CV-BOA-2022-0019",
    "issueDate": "2022-07-15",
    "expiryDate": "2027-07-15",
    "status": "Under Review",
    "registeredAddress": "30 Bofareira Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@palm-capital-investments.cv",
    "contactPhone": "+238 59234 326",
    "businessCategory": "Treasury Outsourcing",
    "complianceNotes": "Maintains bilingual client disclosures in Portuguese and English.",
    "description": "Founded in 2022, Palm Capital Investments operates bespoke FX solutions for renewable energy initiatives throughout Boa Vista.",
    "keyPersons": [
      {
        "name": "Wilma Tavares",
        "role": "Managing Director"
      },
      {
        "name": "Bruno Barbosa",
        "role": "Chief Compliance Officer"
      }
    ]
  },
  {
    "id": 20,
    "slug": "sand-capital-services",
    "companyName": "Sand Capital Services",
    "licenseNumber": "CV-BOA-2023-0020",
    "issueDate": "2023-10-22",
    "expiryDate": "2028-10-22",
    "status": "Suspended",
    "registeredAddress": "31 Estância de Baixo Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@sand-capital-services.cv",
    "contactPhone": "+238 59247 333",
    "businessCategory": "Corporate FX Risk Advisory",
    "complianceNotes": "Operates under conditional approval pending technology platform migration.",
    "description": "Founded in 2023, Sand Capital Services maintains correspondent networks facilitating cross-border commodity trades.",
    "keyPersons": [
      {
        "name": "Yuri Xavier",
        "role": "Chief Compliance Officer"
      },
      {
        "name": "Carla Delgado",
        "role": "Head of Trading"
      },
      {
        "name": "Fabio Lima",
        "role": "Risk Management Lead"
      }
    ]
  },
  {
    "id": 21,
    "slug": "atlantic-channel-advisors",
    "companyName": "Atlantic Channel Advisors",
    "licenseNumber": "CV-BOA-2014-0021",
    "issueDate": "2014-01-01",
    "expiryDate": "2019-01-01",
    "status": "Lapsed",
    "registeredAddress": "32 Povoação Velha Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@atlantic-channel-advisors.cv",
    "contactPhone": "+238 59260 340",
    "businessCategory": "Retail FX Brokerage",
    "complianceNotes": "Maintains quarterly compliance updates with the Boa Vista Financial Authority.",
    "description": "Founded in 2014, Atlantic Channel Advisors delivers currency execution and settlement solutions to the Cape Verdean hospitality and tourism sector.",
    "keyPersons": [
      {
        "name": "Ana Almeida",
        "role": "Head of Trading"
      },
      {
        "name": "Daniel Fernandes",
        "role": "Risk Management Lead"
      }
    ]
  },
  {
    "id": 22,
    "slug": "azure-channel-holdings",
    "companyName": "Azure Channel Holdings",
    "licenseNumber": "CV-BOA-2015-0022",
    "issueDate": "2015-04-08",
    "expiryDate": "N/A",
    "status": "Active",
    "registeredAddress": "33 Rabil Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@azure-channel-holdings.cv",
    "contactPhone": "+238 59273 347",
    "businessCategory": "Institutional FX Brokerage",
    "complianceNotes": "Underwent enhanced due diligence during the most recent supervisory cycle.",
    "description": "Founded in 2015, Azure Channel Holdings supports regional exporters with hedging strategies against Euro and USD volatility.",
    "keyPersons": [
      {
        "name": "Bruno Cardoso",
        "role": "Risk Management Lead"
      },
      {
        "name": "Elisa Henriques",
        "role": "Operations Supervisor"
      },
      {
        "name": "Igor Pereira",
        "role": "Client Relations Principal"
      }
    ]
  },
  {
    "id": 23,
    "slug": "beacon-channel-partners",
    "companyName": "Beacon Channel Partners",
    "licenseNumber": "CV-BOA-2016-0023",
    "issueDate": "2016-07-15",
    "expiryDate": "2021-07-15",
    "status": "Active",
    "registeredAddress": "34 Sal Rei Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@beacon-channel-partners.cv",
    "contactPhone": "+238 59286 354",
    "businessCategory": "Multi-Asset Dealing Desk",
    "complianceNotes": "Submitted revised capital adequacy statement in the last reporting period.",
    "description": "Founded in 2016, Beacon Channel Partners specialises in low-latency order routing for diaspora remittance channels.",
    "keyPersons": [
      {
        "name": "Carla Esteves",
        "role": "Operations Supervisor"
      },
      {
        "name": "Fabio Macedo",
        "role": "Client Relations Principal"
      }
    ]
  },
  {
    "id": 24,
    "slug": "blue-channel-ventures",
    "companyName": "Blue Channel Ventures",
    "licenseNumber": "CV-BOA-2017-0024",
    "issueDate": "2017-10-22",
    "expiryDate": "2022-10-22",
    "status": "Active",
    "registeredAddress": "35 Bofareira Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@blue-channel-ventures.cv",
    "contactPhone": "+238 59299 361",
    "businessCategory": "FX Liquidity Provision",
    "complianceNotes": "Implements mandatory client asset segregation with monthly reconciliations.",
    "description": "Founded in 2017, Blue Channel Ventures partners with local banks to provide treasury outsourcing and liquidity management.",
    "keyPersons": [
      {
        "name": "Daniel Gomes",
        "role": "Client Relations Principal"
      },
      {
        "name": "Helena Oliveira",
        "role": "Managing Director"
      },
      {
        "name": "Luis Tavares",
        "role": "Chief Compliance Officer"
      }
    ]
  },
  {
    "id": 25,
    "slug": "coral-channel-consulting",
    "companyName": "Coral Channel Consulting",
    "licenseNumber": "CV-BOA-2018-0025",
    "issueDate": "2018-01-01",
    "expiryDate": "2023-01-01",
    "status": "Active",
    "registeredAddress": "36 Estância de Baixo Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@coral-channel-consulting.cv",
    "contactPhone": "+238 59312 368",
    "businessCategory": "Commodities Brokerage",
    "complianceNotes": "Participates in cross-border information sharing with Lusophone regulators.",
    "description": "Founded in 2018, Coral Channel Consulting offers portfolio diversification tools for high-net-worth investors across West Africa.",
    "keyPersons": [
      {
        "name": "Elisa Lima",
        "role": "Managing Director"
      },
      {
        "name": "Igor Quintino",
        "role": "Chief Compliance Officer"
      }
    ]
  },
  {
    "id": 26,
    "slug": "emerald-channel-markets",
    "companyName": "Emerald Channel Markets",
    "licenseNumber": "CV-BOA-2019-0026",
    "issueDate": "2019-04-08",
    "expiryDate": "2024-04-08",
    "status": "Under Review",
    "registeredAddress": "37 Povoação Velha Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@emerald-channel-markets.cv",
    "contactPhone": "+238 59325 375",
    "businessCategory": "Derivatives Advisory",
    "complianceNotes": "Filed updated disaster recovery plan incorporating offshore redundancy.",
    "description": "Founded in 2019, Emerald Channel Markets focuses on sustainable finance instruments linked to island infrastructure projects.",
    "keyPersons": [
      {
        "name": "Fabio Neves",
        "role": "Chief Compliance Officer"
      },
      {
        "name": "Joana Silva",
        "role": "Head of Trading"
      },
      {
        "name": "Nuno Almeida",
        "role": "Risk Management Lead"
      }
    ]
  },
  {
    "id": 27,
    "slug": "harbor-channel-trust",
    "companyName": "Harbor Channel Trust",
    "licenseNumber": "CV-BOA-2020-0027",
    "issueDate": "2020-07-15",
    "expiryDate": "2025-07-15",
    "status": "Suspended",
    "registeredAddress": "38 Rabil Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@harbor-channel-trust.cv",
    "contactPhone": "+238 59338 382",
    "businessCategory": "Wealth Management Services",
    "complianceNotes": "Completed independent AML/CTF audit with satisfactory findings.",
    "description": "Founded in 2020, Harbor Channel Trust implements disciplined risk management tailored to maritime shipping clients.",
    "keyPersons": [
      {
        "name": "Helena Pereira",
        "role": "Head of Trading"
      },
      {
        "name": "Luis Vidal",
        "role": "Risk Management Lead"
      }
    ]
  },
  {
    "id": 28,
    "slug": "mariner-channel-associates",
    "companyName": "Mariner Channel Associates",
    "licenseNumber": "CV-BOA-2021-0028",
    "issueDate": "2021-10-22",
    "expiryDate": "2026-10-22",
    "status": "Lapsed",
    "registeredAddress": "39 Sal Rei Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@mariner-channel-associates.cv",
    "contactPhone": "+238 59351 389",
    "businessCategory": "Payment and Remittance Services",
    "complianceNotes": "Subject to annual prudential assessment focusing on liquidity buffers.",
    "description": "Founded in 2021, Mariner Channel Associates provides onboarding support for fintech entrants expanding into Lusophone markets.",
    "keyPersons": [
      {
        "name": "Igor Ramos",
        "role": "Risk Management Lead"
      },
      {
        "name": "Marta Zamora",
        "role": "Operations Supervisor"
      },
      {
        "name": "Paulo Esteves",
        "role": "Client Relations Principal"
      }
    ]
  },
  {
    "id": 29,
    "slug": "palm-channel-investments",
    "companyName": "Palm Channel Investments",
    "licenseNumber": "CV-BOA-2022-0029",
    "issueDate": "2022-01-01",
    "expiryDate": "N/A",
    "status": "Active",
    "registeredAddress": "40 Bofareira Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@palm-channel-investments.cv",
    "contactPhone": "+238 59364 396",
    "businessCategory": "Treasury Outsourcing",
    "complianceNotes": "Maintains bilingual client disclosures in Portuguese and English.",
    "description": "Founded in 2022, Palm Channel Investments operates bespoke FX solutions for renewable energy initiatives throughout Boa Vista.",
    "keyPersons": [
      {
        "name": "Joana Tavares",
        "role": "Operations Supervisor"
      },
      {
        "name": "Nuno Barbosa",
        "role": "Client Relations Principal"
      }
    ]
  },
  {
    "id": 30,
    "slug": "sand-channel-services",
    "companyName": "Sand Channel Services",
    "licenseNumber": "CV-BOA-2023-0030",
    "issueDate": "2023-04-08",
    "expiryDate": "2028-04-08",
    "status": "Active",
    "registeredAddress": "41 Estância de Baixo Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@sand-channel-services.cv",
    "contactPhone": "+238 59377 403",
    "businessCategory": "Corporate FX Risk Advisory",
    "complianceNotes": "Operates under conditional approval pending technology platform migration.",
    "description": "Founded in 2023, Sand Channel Services maintains correspondent networks facilitating cross-border commodity trades.",
    "keyPersons": [
      {
        "name": "Luis Xavier",
        "role": "Client Relations Principal"
      },
      {
        "name": "Olivia Delgado",
        "role": "Managing Director"
      },
      {
        "name": "Sergio Lima",
        "role": "Chief Compliance Officer"
      }
    ]
  },
  {
    "id": 31,
    "slug": "atlantic-coast-advisors",
    "companyName": "Atlantic Coast Advisors",
    "licenseNumber": "CV-BOA-2014-0031",
    "issueDate": "2014-07-15",
    "expiryDate": "2019-07-15",
    "status": "Active",
    "registeredAddress": "42 Povoação Velha Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@atlantic-coast-advisors.cv",
    "contactPhone": "+238 59390 410",
    "businessCategory": "Retail FX Brokerage",
    "complianceNotes": "Maintains quarterly compliance updates with the Boa Vista Financial Authority.",
    "description": "Founded in 2014, Atlantic Coast Advisors delivers currency execution and settlement solutions to the Cape Verdean hospitality and tourism sector.",
    "keyPersons": [
      {
        "name": "Marta Almeida",
        "role": "Managing Director"
      },
      {
        "name": "Paulo Fernandes",
        "role": "Chief Compliance Officer"
      }
    ]
  },
  {
    "id": 32,
    "slug": "azure-coast-holdings",
    "companyName": "Azure Coast Holdings",
    "licenseNumber": "CV-BOA-2015-0032",
    "issueDate": "2015-10-22",
    "expiryDate": "2020-10-22",
    "status": "Active",
    "registeredAddress": "43 Rabil Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@azure-coast-holdings.cv",
    "contactPhone": "+238 59403 417",
    "businessCategory": "Institutional FX Brokerage",
    "complianceNotes": "Underwent enhanced due diligence during the most recent supervisory cycle.",
    "description": "Founded in 2015, Azure Coast Holdings supports regional exporters with hedging strategies against Euro and USD volatility.",
    "keyPersons": [
      {
        "name": "Nuno Cardoso",
        "role": "Chief Compliance Officer"
      },
      {
        "name": "Rita Henriques",
        "role": "Head of Trading"
      },
      {
        "name": "Vasco Pereira",
        "role": "Risk Management Lead"
      }
    ]
  },
  {
    "id": 33,
    "slug": "beacon-coast-partners",
    "companyName": "Beacon Coast Partners",
    "licenseNumber": "CV-BOA-2016-0033",
    "issueDate": "2016-01-01",
    "expiryDate": "2021-01-01",
    "status": "Under Review",
    "registeredAddress": "44 Sal Rei Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@beacon-coast-partners.cv",
    "contactPhone": "+238 59416 424",
    "businessCategory": "Multi-Asset Dealing Desk",
    "complianceNotes": "Submitted revised capital adequacy statement in the last reporting period.",
    "description": "Founded in 2016, Beacon Coast Partners specialises in low-latency order routing for diaspora remittance channels.",
    "keyPersons": [
      {
        "name": "Olivia Esteves",
        "role": "Head of Trading"
      },
      {
        "name": "Sergio Macedo",
        "role": "Risk Management Lead"
      }
    ]
  },
  {
    "id": 34,
    "slug": "blue-coast-ventures",
    "companyName": "Blue Coast Ventures",
    "licenseNumber": "CV-BOA-2017-0034",
    "issueDate": "2017-04-08",
    "expiryDate": "2022-04-08",
    "status": "Suspended",
    "registeredAddress": "45 Bofareira Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@blue-coast-ventures.cv",
    "contactPhone": "+238 59429 431",
    "businessCategory": "FX Liquidity Provision",
    "complianceNotes": "Implements mandatory client asset segregation with monthly reconciliations.",
    "description": "Founded in 2017, Blue Coast Ventures partners with local banks to provide treasury outsourcing and liquidity management.",
    "keyPersons": [
      {
        "name": "Paulo Gomes",
        "role": "Risk Management Lead"
      },
      {
        "name": "Teresa Oliveira",
        "role": "Operations Supervisor"
      },
      {
        "name": "Yuri Tavares",
        "role": "Client Relations Principal"
      }
    ]
  },
  {
    "id": 35,
    "slug": "coral-coast-consulting",
    "companyName": "Coral Coast Consulting",
    "licenseNumber": "CV-BOA-2018-0035",
    "issueDate": "2018-07-15",
    "expiryDate": "2023-07-15",
    "status": "Lapsed",
    "registeredAddress": "46 Estância de Baixo Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@coral-coast-consulting.cv",
    "contactPhone": "+238 59442 438",
    "businessCategory": "Commodities Brokerage",
    "complianceNotes": "Participates in cross-border information sharing with Lusophone regulators.",
    "description": "Founded in 2018, Coral Coast Consulting offers portfolio diversification tools for high-net-worth investors across West Africa.",
    "keyPersons": [
      {
        "name": "Rita Lima",
        "role": "Operations Supervisor"
      },
      {
        "name": "Vasco Quintino",
        "role": "Client Relations Principal"
      }
    ]
  },
  {
    "id": 36,
    "slug": "emerald-coast-markets",
    "companyName": "Emerald Coast Markets",
    "licenseNumber": "CV-BOA-2019-0036",
    "issueDate": "2019-10-22",
    "expiryDate": "N/A",
    "status": "Active",
    "registeredAddress": "47 Povoação Velha Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@emerald-coast-markets.cv",
    "contactPhone": "+238 59455 445",
    "businessCategory": "Derivatives Advisory",
    "complianceNotes": "Filed updated disaster recovery plan incorporating offshore redundancy.",
    "description": "Founded in 2019, Emerald Coast Markets focuses on sustainable finance instruments linked to island infrastructure projects.",
    "keyPersons": [
      {
        "name": "Sergio Neves",
        "role": "Client Relations Principal"
      },
      {
        "name": "Wilma Silva",
        "role": "Managing Director"
      },
      {
        "name": "Bruno Almeida",
        "role": "Chief Compliance Officer"
      }
    ]
  },
  {
    "id": 37,
    "slug": "harbor-coast-trust",
    "companyName": "Harbor Coast Trust",
    "licenseNumber": "CV-BOA-2020-0037",
    "issueDate": "2020-01-01",
    "expiryDate": "2025-01-01",
    "status": "Active",
    "registeredAddress": "48 Rabil Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@harbor-coast-trust.cv",
    "contactPhone": "+238 59468 452",
    "businessCategory": "Wealth Management Services",
    "complianceNotes": "Completed independent AML/CTF audit with satisfactory findings.",
    "description": "Founded in 2020, Harbor Coast Trust implements disciplined risk management tailored to maritime shipping clients.",
    "keyPersons": [
      {
        "name": "Teresa Pereira",
        "role": "Managing Director"
      },
      {
        "name": "Yuri Vidal",
        "role": "Chief Compliance Officer"
      }
    ]
  },
  {
    "id": 38,
    "slug": "mariner-coast-associates",
    "companyName": "Mariner Coast Associates",
    "licenseNumber": "CV-BOA-2021-0038",
    "issueDate": "2021-04-08",
    "expiryDate": "2026-04-08",
    "status": "Active",
    "registeredAddress": "49 Sal Rei Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@mariner-coast-associates.cv",
    "contactPhone": "+238 59481 459",
    "businessCategory": "Payment and Remittance Services",
    "complianceNotes": "Subject to annual prudential assessment focusing on liquidity buffers.",
    "description": "Founded in 2021, Mariner Coast Associates provides onboarding support for fintech entrants expanding into Lusophone markets.",
    "keyPersons": [
      {
        "name": "Vasco Ramos",
        "role": "Chief Compliance Officer"
      },
      {
        "name": "Ana Zamora",
        "role": "Head of Trading"
      },
      {
        "name": "Daniel Esteves",
        "role": "Risk Management Lead"
      }
    ]
  },
  {
    "id": 39,
    "slug": "palm-coast-investments",
    "companyName": "Palm Coast Investments",
    "licenseNumber": "CV-BOA-2022-0039",
    "issueDate": "2022-07-15",
    "expiryDate": "2027-07-15",
    "status": "Active",
    "registeredAddress": "50 Bofareira Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@palm-coast-investments.cv",
    "contactPhone": "+238 59494 466",
    "businessCategory": "Treasury Outsourcing",
    "complianceNotes": "Maintains bilingual client disclosures in Portuguese and English.",
    "description": "Founded in 2022, Palm Coast Investments operates bespoke FX solutions for renewable energy initiatives throughout Boa Vista.",
    "keyPersons": [
      {
        "name": "Wilma Tavares",
        "role": "Head of Trading"
      },
      {
        "name": "Bruno Barbosa",
        "role": "Risk Management Lead"
      }
    ]
  },
  {
    "id": 40,
    "slug": "sand-coast-services",
    "companyName": "Sand Coast Services",
    "licenseNumber": "CV-BOA-2023-0040",
    "issueDate": "2023-10-22",
    "expiryDate": "2028-10-22",
    "status": "Under Review",
    "registeredAddress": "51 Estância de Baixo Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@sand-coast-services.cv",
    "contactPhone": "+238 59507 473",
    "businessCategory": "Corporate FX Risk Advisory",
    "complianceNotes": "Operates under conditional approval pending technology platform migration.",
    "description": "Founded in 2023, Sand Coast Services maintains correspondent networks facilitating cross-border commodity trades.",
    "keyPersons": [
      {
        "name": "Yuri Xavier",
        "role": "Risk Management Lead"
      },
      {
        "name": "Carla Delgado",
        "role": "Operations Supervisor"
      },
      {
        "name": "Fabio Lima",
        "role": "Client Relations Principal"
      }
    ]
  },
  {
    "id": 41,
    "slug": "atlantic-crest-advisors",
    "companyName": "Atlantic Crest Advisors",
    "licenseNumber": "CV-BOA-2014-0041",
    "issueDate": "2014-01-01",
    "expiryDate": "2019-01-01",
    "status": "Suspended",
    "registeredAddress": "52 Povoação Velha Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@atlantic-crest-advisors.cv",
    "contactPhone": "+238 59520 480",
    "businessCategory": "Retail FX Brokerage",
    "complianceNotes": "Maintains quarterly compliance updates with the Boa Vista Financial Authority.",
    "description": "Founded in 2014, Atlantic Crest Advisors delivers currency execution and settlement solutions to the Cape Verdean hospitality and tourism sector.",
    "keyPersons": [
      {
        "name": "Ana Almeida",
        "role": "Operations Supervisor"
      },
      {
        "name": "Daniel Fernandes",
        "role": "Client Relations Principal"
      }
    ]
  },
  {
    "id": 42,
    "slug": "azure-crest-holdings",
    "companyName": "Azure Crest Holdings",
    "licenseNumber": "CV-BOA-2015-0042",
    "issueDate": "2015-04-08",
    "expiryDate": "2020-04-08",
    "status": "Lapsed",
    "registeredAddress": "53 Rabil Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@azure-crest-holdings.cv",
    "contactPhone": "+238 59533 487",
    "businessCategory": "Institutional FX Brokerage",
    "complianceNotes": "Underwent enhanced due diligence during the most recent supervisory cycle.",
    "description": "Founded in 2015, Azure Crest Holdings supports regional exporters with hedging strategies against Euro and USD volatility.",
    "keyPersons": [
      {
        "name": "Bruno Cardoso",
        "role": "Client Relations Principal"
      },
      {
        "name": "Elisa Henriques",
        "role": "Managing Director"
      },
      {
        "name": "Igor Pereira",
        "role": "Chief Compliance Officer"
      }
    ]
  },
  {
    "id": 43,
    "slug": "beacon-crest-partners",
    "companyName": "Beacon Crest Partners",
    "licenseNumber": "CV-BOA-2016-0043",
    "issueDate": "2016-07-15",
    "expiryDate": "N/A",
    "status": "Active",
    "registeredAddress": "54 Sal Rei Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@beacon-crest-partners.cv",
    "contactPhone": "+238 59546 494",
    "businessCategory": "Multi-Asset Dealing Desk",
    "complianceNotes": "Submitted revised capital adequacy statement in the last reporting period.",
    "description": "Founded in 2016, Beacon Crest Partners specialises in low-latency order routing for diaspora remittance channels.",
    "keyPersons": [
      {
        "name": "Carla Esteves",
        "role": "Managing Director"
      },
      {
        "name": "Fabio Macedo",
        "role": "Chief Compliance Officer"
      }
    ]
  },
  {
    "id": 44,
    "slug": "blue-crest-ventures",
    "companyName": "Blue Crest Ventures",
    "licenseNumber": "CV-BOA-2017-0044",
    "issueDate": "2017-10-22",
    "expiryDate": "2022-10-22",
    "status": "Active",
    "registeredAddress": "55 Bofareira Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@blue-crest-ventures.cv",
    "contactPhone": "+238 59559 501",
    "businessCategory": "FX Liquidity Provision",
    "complianceNotes": "Implements mandatory client asset segregation with monthly reconciliations.",
    "description": "Founded in 2017, Blue Crest Ventures partners with local banks to provide treasury outsourcing and liquidity management.",
    "keyPersons": [
      {
        "name": "Daniel Gomes",
        "role": "Chief Compliance Officer"
      },
      {
        "name": "Helena Oliveira",
        "role": "Head of Trading"
      },
      {
        "name": "Luis Tavares",
        "role": "Risk Management Lead"
      }
    ]
  },
  {
    "id": 45,
    "slug": "coral-crest-consulting",
    "companyName": "Coral Crest Consulting",
    "licenseNumber": "CV-BOA-2018-0045",
    "issueDate": "2018-01-01",
    "expiryDate": "2023-01-01",
    "status": "Active",
    "registeredAddress": "56 Estância de Baixo Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@coral-crest-consulting.cv",
    "contactPhone": "+238 59572 508",
    "businessCategory": "Commodities Brokerage",
    "complianceNotes": "Participates in cross-border information sharing with Lusophone regulators.",
    "description": "Founded in 2018, Coral Crest Consulting offers portfolio diversification tools for high-net-worth investors across West Africa.",
    "keyPersons": [
      {
        "name": "Elisa Lima",
        "role": "Head of Trading"
      },
      {
        "name": "Igor Quintino",
        "role": "Risk Management Lead"
      }
    ]
  },
  {
    "id": 46,
    "slug": "emerald-crest-markets",
    "companyName": "Emerald Crest Markets",
    "licenseNumber": "CV-BOA-2019-0046",
    "issueDate": "2019-04-08",
    "expiryDate": "2024-04-08",
    "status": "Active",
    "registeredAddress": "57 Povoação Velha Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@emerald-crest-markets.cv",
    "contactPhone": "+238 59585 515",
    "businessCategory": "Derivatives Advisory",
    "complianceNotes": "Filed updated disaster recovery plan incorporating offshore redundancy.",
    "description": "Founded in 2019, Emerald Crest Markets focuses on sustainable finance instruments linked to island infrastructure projects.",
    "keyPersons": [
      {
        "name": "Fabio Neves",
        "role": "Risk Management Lead"
      },
      {
        "name": "Joana Silva",
        "role": "Operations Supervisor"
      },
      {
        "name": "Nuno Almeida",
        "role": "Client Relations Principal"
      }
    ]
  },
  {
    "id": 47,
    "slug": "harbor-crest-trust",
    "companyName": "Harbor Crest Trust",
    "licenseNumber": "CV-BOA-2020-0047",
    "issueDate": "2020-07-15",
    "expiryDate": "2025-07-15",
    "status": "Under Review",
    "registeredAddress": "58 Rabil Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@harbor-crest-trust.cv",
    "contactPhone": "+238 59598 522",
    "businessCategory": "Wealth Management Services",
    "complianceNotes": "Completed independent AML/CTF audit with satisfactory findings.",
    "description": "Founded in 2020, Harbor Crest Trust implements disciplined risk management tailored to maritime shipping clients.",
    "keyPersons": [
      {
        "name": "Helena Pereira",
        "role": "Operations Supervisor"
      },
      {
        "name": "Luis Vidal",
        "role": "Client Relations Principal"
      }
    ]
  },
  {
    "id": 48,
    "slug": "mariner-crest-associates",
    "companyName": "Mariner Crest Associates",
    "licenseNumber": "CV-BOA-2021-0048",
    "issueDate": "2021-10-22",
    "expiryDate": "2026-10-22",
    "status": "Suspended",
    "registeredAddress": "59 Sal Rei Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@mariner-crest-associates.cv",
    "contactPhone": "+238 59611 529",
    "businessCategory": "Payment and Remittance Services",
    "complianceNotes": "Subject to annual prudential assessment focusing on liquidity buffers.",
    "description": "Founded in 2021, Mariner Crest Associates provides onboarding support for fintech entrants expanding into Lusophone markets.",
    "keyPersons": [
      {
        "name": "Igor Ramos",
        "role": "Client Relations Principal"
      },
      {
        "name": "Marta Zamora",
        "role": "Managing Director"
      },
      {
        "name": "Paulo Esteves",
        "role": "Chief Compliance Officer"
      }
    ]
  },
  {
    "id": 49,
    "slug": "palm-crest-investments",
    "companyName": "Palm Crest Investments",
    "licenseNumber": "CV-BOA-2022-0049",
    "issueDate": "2022-01-01",
    "expiryDate": "2027-01-01",
    "status": "Lapsed",
    "registeredAddress": "60 Bofareira Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@palm-crest-investments.cv",
    "contactPhone": "+238 59624 536",
    "businessCategory": "Treasury Outsourcing",
    "complianceNotes": "Maintains bilingual client disclosures in Portuguese and English.",
    "description": "Founded in 2022, Palm Crest Investments operates bespoke FX solutions for renewable energy initiatives throughout Boa Vista.",
    "keyPersons": [
      {
        "name": "Joana Tavares",
        "role": "Managing Director"
      },
      {
        "name": "Nuno Barbosa",
        "role": "Chief Compliance Officer"
      }
    ]
  },
  {
    "id": 50,
    "slug": "sand-crest-services",
    "companyName": "Sand Crest Services",
    "licenseNumber": "CV-BOA-2023-0050",
    "issueDate": "2023-04-08",
    "expiryDate": "N/A",
    "status": "Active",
    "registeredAddress": "61 Estância de Baixo Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@sand-crest-services.cv",
    "contactPhone": "+238 59637 543",
    "businessCategory": "Corporate FX Risk Advisory",
    "complianceNotes": "Operates under conditional approval pending technology platform migration.",
    "description": "Founded in 2023, Sand Crest Services maintains correspondent networks facilitating cross-border commodity trades.",
    "keyPersons": [
      {
        "name": "Luis Xavier",
        "role": "Chief Compliance Officer"
      },
      {
        "name": "Olivia Delgado",
        "role": "Head of Trading"
      },
      {
        "name": "Sergio Lima",
        "role": "Risk Management Lead"
      }
    ]
  },
  {
    "id": 51,
    "slug": "atlantic-harbor-advisors",
    "companyName": "Atlantic Harbor Advisors",
    "licenseNumber": "CV-BOA-2014-0051",
    "issueDate": "2014-07-15",
    "expiryDate": "2019-07-15",
    "status": "Active",
    "registeredAddress": "62 Povoação Velha Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@atlantic-harbor-advisors.cv",
    "contactPhone": "+238 59650 550",
    "businessCategory": "Retail FX Brokerage",
    "complianceNotes": "Maintains quarterly compliance updates with the Boa Vista Financial Authority.",
    "description": "Founded in 2014, Atlantic Harbor Advisors delivers currency execution and settlement solutions to the Cape Verdean hospitality and tourism sector.",
    "keyPersons": [
      {
        "name": "Marta Almeida",
        "role": "Head of Trading"
      },
      {
        "name": "Paulo Fernandes",
        "role": "Risk Management Lead"
      }
    ]
  },
  {
    "id": 52,
    "slug": "azure-harbor-holdings",
    "companyName": "Azure Harbor Holdings",
    "licenseNumber": "CV-BOA-2015-0052",
    "issueDate": "2015-10-22",
    "expiryDate": "2020-10-22",
    "status": "Active",
    "registeredAddress": "63 Rabil Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@azure-harbor-holdings.cv",
    "contactPhone": "+238 59663 557",
    "businessCategory": "Institutional FX Brokerage",
    "complianceNotes": "Underwent enhanced due diligence during the most recent supervisory cycle.",
    "description": "Founded in 2015, Azure Harbor Holdings supports regional exporters with hedging strategies against Euro and USD volatility.",
    "keyPersons": [
      {
        "name": "Nuno Cardoso",
        "role": "Risk Management Lead"
      },
      {
        "name": "Rita Henriques",
        "role": "Operations Supervisor"
      },
      {
        "name": "Vasco Pereira",
        "role": "Client Relations Principal"
      }
    ]
  },
  {
    "id": 53,
    "slug": "beacon-harbor-partners",
    "companyName": "Beacon Harbor Partners",
    "licenseNumber": "CV-BOA-2016-0053",
    "issueDate": "2016-01-01",
    "expiryDate": "2021-01-01",
    "status": "Active",
    "registeredAddress": "64 Sal Rei Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@beacon-harbor-partners.cv",
    "contactPhone": "+238 59676 564",
    "businessCategory": "Multi-Asset Dealing Desk",
    "complianceNotes": "Submitted revised capital adequacy statement in the last reporting period.",
    "description": "Founded in 2016, Beacon Harbor Partners specialises in low-latency order routing for diaspora remittance channels.",
    "keyPersons": [
      {
        "name": "Olivia Esteves",
        "role": "Operations Supervisor"
      },
      {
        "name": "Sergio Macedo",
        "role": "Client Relations Principal"
      }
    ]
  },
  {
    "id": 54,
    "slug": "blue-harbor-ventures",
    "companyName": "Blue Harbor Ventures",
    "licenseNumber": "CV-BOA-2017-0054",
    "issueDate": "2017-04-08",
    "expiryDate": "2022-04-08",
    "status": "Under Review",
    "registeredAddress": "65 Bofareira Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@blue-harbor-ventures.cv",
    "contactPhone": "+238 59689 571",
    "businessCategory": "FX Liquidity Provision",
    "complianceNotes": "Implements mandatory client asset segregation with monthly reconciliations.",
    "description": "Founded in 2017, Blue Harbor Ventures partners with local banks to provide treasury outsourcing and liquidity management.",
    "keyPersons": [
      {
        "name": "Paulo Gomes",
        "role": "Client Relations Principal"
      },
      {
        "name": "Teresa Oliveira",
        "role": "Managing Director"
      },
      {
        "name": "Yuri Tavares",
        "role": "Chief Compliance Officer"
      }
    ]
  },
  {
    "id": 55,
    "slug": "coral-harbor-consulting",
    "companyName": "Coral Harbor Consulting",
    "licenseNumber": "CV-BOA-2018-0055",
    "issueDate": "2018-07-15",
    "expiryDate": "2023-07-15",
    "status": "Suspended",
    "registeredAddress": "66 Estância de Baixo Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@coral-harbor-consulting.cv",
    "contactPhone": "+238 59702 578",
    "businessCategory": "Commodities Brokerage",
    "complianceNotes": "Participates in cross-border information sharing with Lusophone regulators.",
    "description": "Founded in 2018, Coral Harbor Consulting offers portfolio diversification tools for high-net-worth investors across West Africa.",
    "keyPersons": [
      {
        "name": "Rita Lima",
        "role": "Managing Director"
      },
      {
        "name": "Vasco Quintino",
        "role": "Chief Compliance Officer"
      }
    ]
  },
  {
    "id": 56,
    "slug": "emerald-harbor-markets",
    "companyName": "Emerald Harbor Markets",
    "licenseNumber": "CV-BOA-2019-0056",
    "issueDate": "2019-10-22",
    "expiryDate": "2024-10-22",
    "status": "Lapsed",
    "registeredAddress": "67 Povoação Velha Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@emerald-harbor-markets.cv",
    "contactPhone": "+238 59715 585",
    "businessCategory": "Derivatives Advisory",
    "complianceNotes": "Filed updated disaster recovery plan incorporating offshore redundancy.",
    "description": "Founded in 2019, Emerald Harbor Markets focuses on sustainable finance instruments linked to island infrastructure projects.",
    "keyPersons": [
      {
        "name": "Sergio Neves",
        "role": "Chief Compliance Officer"
      },
      {
        "name": "Wilma Silva",
        "role": "Head of Trading"
      },
      {
        "name": "Bruno Almeida",
        "role": "Risk Management Lead"
      }
    ]
  },
  {
    "id": 57,
    "slug": "harbor-harbor-trust",
    "companyName": "Harbor Harbor Trust",
    "licenseNumber": "CV-BOA-2020-0057",
    "issueDate": "2020-01-01",
    "expiryDate": "N/A",
    "status": "Active",
    "registeredAddress": "68 Rabil Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@harbor-harbor-trust.cv",
    "contactPhone": "+238 59728 592",
    "businessCategory": "Wealth Management Services",
    "complianceNotes": "Completed independent AML/CTF audit with satisfactory findings.",
    "description": "Founded in 2020, Harbor Harbor Trust implements disciplined risk management tailored to maritime shipping clients.",
    "keyPersons": [
      {
        "name": "Teresa Pereira",
        "role": "Head of Trading"
      },
      {
        "name": "Yuri Vidal",
        "role": "Risk Management Lead"
      }
    ]
  },
  {
    "id": 58,
    "slug": "mariner-harbor-associates",
    "companyName": "Mariner Harbor Associates",
    "licenseNumber": "CV-BOA-2021-0058",
    "issueDate": "2021-04-08",
    "expiryDate": "2026-04-08",
    "status": "Active",
    "registeredAddress": "69 Sal Rei Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@mariner-harbor-associates.cv",
    "contactPhone": "+238 59741 599",
    "businessCategory": "Payment and Remittance Services",
    "complianceNotes": "Subject to annual prudential assessment focusing on liquidity buffers.",
    "description": "Founded in 2021, Mariner Harbor Associates provides onboarding support for fintech entrants expanding into Lusophone markets.",
    "keyPersons": [
      {
        "name": "Vasco Ramos",
        "role": "Risk Management Lead"
      },
      {
        "name": "Ana Zamora",
        "role": "Operations Supervisor"
      },
      {
        "name": "Daniel Esteves",
        "role": "Client Relations Principal"
      }
    ]
  },
  {
    "id": 59,
    "slug": "palm-harbor-investments",
    "companyName": "Palm Harbor Investments",
    "licenseNumber": "CV-BOA-2022-0059",
    "issueDate": "2022-07-15",
    "expiryDate": "2027-07-15",
    "status": "Active",
    "registeredAddress": "70 Bofareira Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@palm-harbor-investments.cv",
    "contactPhone": "+238 59754 606",
    "businessCategory": "Treasury Outsourcing",
    "complianceNotes": "Maintains bilingual client disclosures in Portuguese and English.",
    "description": "Founded in 2022, Palm Harbor Investments operates bespoke FX solutions for renewable energy initiatives throughout Boa Vista.",
    "keyPersons": [
      {
        "name": "Wilma Tavares",
        "role": "Operations Supervisor"
      },
      {
        "name": "Bruno Barbosa",
        "role": "Client Relations Principal"
      }
    ]
  },
  {
    "id": 60,
    "slug": "sand-harbor-services",
    "companyName": "Sand Harbor Services",
    "licenseNumber": "CV-BOA-2023-0060",
    "issueDate": "2023-10-22",
    "expiryDate": "2028-10-22",
    "status": "Active",
    "registeredAddress": "71 Estância de Baixo Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@sand-harbor-services.cv",
    "contactPhone": "+238 59767 613",
    "businessCategory": "Corporate FX Risk Advisory",
    "complianceNotes": "Operates under conditional approval pending technology platform migration.",
    "description": "Founded in 2023, Sand Harbor Services maintains correspondent networks facilitating cross-border commodity trades.",
    "keyPersons": [
      {
        "name": "Yuri Xavier",
        "role": "Client Relations Principal"
      },
      {
        "name": "Carla Delgado",
        "role": "Managing Director"
      },
      {
        "name": "Fabio Lima",
        "role": "Chief Compliance Officer"
      }
    ]
  },
  {
    "id": 61,
    "slug": "atlantic-horizon-advisors",
    "companyName": "Atlantic Horizon Advisors",
    "licenseNumber": "CV-BOA-2014-0061",
    "issueDate": "2014-01-01",
    "expiryDate": "2019-01-01",
    "status": "Under Review",
    "registeredAddress": "72 Povoação Velha Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@atlantic-horizon-advisors.cv",
    "contactPhone": "+238 59780 620",
    "businessCategory": "Retail FX Brokerage",
    "complianceNotes": "Maintains quarterly compliance updates with the Boa Vista Financial Authority.",
    "description": "Founded in 2014, Atlantic Horizon Advisors delivers currency execution and settlement solutions to the Cape Verdean hospitality and tourism sector.",
    "keyPersons": [
      {
        "name": "Ana Almeida",
        "role": "Managing Director"
      },
      {
        "name": "Daniel Fernandes",
        "role": "Chief Compliance Officer"
      }
    ]
  },
  {
    "id": 62,
    "slug": "azure-horizon-holdings",
    "companyName": "Azure Horizon Holdings",
    "licenseNumber": "CV-BOA-2015-0062",
    "issueDate": "2015-04-08",
    "expiryDate": "2020-04-08",
    "status": "Suspended",
    "registeredAddress": "73 Rabil Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@azure-horizon-holdings.cv",
    "contactPhone": "+238 59793 627",
    "businessCategory": "Institutional FX Brokerage",
    "complianceNotes": "Underwent enhanced due diligence during the most recent supervisory cycle.",
    "description": "Founded in 2015, Azure Horizon Holdings supports regional exporters with hedging strategies against Euro and USD volatility.",
    "keyPersons": [
      {
        "name": "Bruno Cardoso",
        "role": "Chief Compliance Officer"
      },
      {
        "name": "Elisa Henriques",
        "role": "Head of Trading"
      },
      {
        "name": "Igor Pereira",
        "role": "Risk Management Lead"
      }
    ]
  },
  {
    "id": 63,
    "slug": "beacon-horizon-partners",
    "companyName": "Beacon Horizon Partners",
    "licenseNumber": "CV-BOA-2016-0063",
    "issueDate": "2016-07-15",
    "expiryDate": "2021-07-15",
    "status": "Lapsed",
    "registeredAddress": "74 Sal Rei Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@beacon-horizon-partners.cv",
    "contactPhone": "+238 59806 634",
    "businessCategory": "Multi-Asset Dealing Desk",
    "complianceNotes": "Submitted revised capital adequacy statement in the last reporting period.",
    "description": "Founded in 2016, Beacon Horizon Partners specialises in low-latency order routing for diaspora remittance channels.",
    "keyPersons": [
      {
        "name": "Carla Esteves",
        "role": "Head of Trading"
      },
      {
        "name": "Fabio Macedo",
        "role": "Risk Management Lead"
      }
    ]
  },
  {
    "id": 64,
    "slug": "blue-horizon-ventures",
    "companyName": "Blue Horizon Ventures",
    "licenseNumber": "CV-BOA-2017-0064",
    "issueDate": "2017-10-22",
    "expiryDate": "N/A",
    "status": "Active",
    "registeredAddress": "75 Bofareira Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@blue-horizon-ventures.cv",
    "contactPhone": "+238 59819 641",
    "businessCategory": "FX Liquidity Provision",
    "complianceNotes": "Implements mandatory client asset segregation with monthly reconciliations.",
    "description": "Founded in 2017, Blue Horizon Ventures partners with local banks to provide treasury outsourcing and liquidity management.",
    "keyPersons": [
      {
        "name": "Daniel Gomes",
        "role": "Risk Management Lead"
      },
      {
        "name": "Helena Oliveira",
        "role": "Operations Supervisor"
      },
      {
        "name": "Luis Tavares",
        "role": "Client Relations Principal"
      }
    ]
  },
  {
    "id": 65,
    "slug": "coral-horizon-consulting",
    "companyName": "Coral Horizon Consulting",
    "licenseNumber": "CV-BOA-2018-0065",
    "issueDate": "2018-01-01",
    "expiryDate": "2023-01-01",
    "status": "Active",
    "registeredAddress": "76 Estância de Baixo Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@coral-horizon-consulting.cv",
    "contactPhone": "+238 59832 648",
    "businessCategory": "Commodities Brokerage",
    "complianceNotes": "Participates in cross-border information sharing with Lusophone regulators.",
    "description": "Founded in 2018, Coral Horizon Consulting offers portfolio diversification tools for high-net-worth investors across West Africa.",
    "keyPersons": [
      {
        "name": "Elisa Lima",
        "role": "Operations Supervisor"
      },
      {
        "name": "Igor Quintino",
        "role": "Client Relations Principal"
      }
    ]
  },
  {
    "id": 66,
    "slug": "emerald-horizon-markets",
    "companyName": "Emerald Horizon Markets",
    "licenseNumber": "CV-BOA-2019-0066",
    "issueDate": "2019-04-08",
    "expiryDate": "2024-04-08",
    "status": "Active",
    "registeredAddress": "77 Povoação Velha Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@emerald-horizon-markets.cv",
    "contactPhone": "+238 59845 655",
    "businessCategory": "Derivatives Advisory",
    "complianceNotes": "Filed updated disaster recovery plan incorporating offshore redundancy.",
    "description": "Founded in 2019, Emerald Horizon Markets focuses on sustainable finance instruments linked to island infrastructure projects.",
    "keyPersons": [
      {
        "name": "Fabio Neves",
        "role": "Client Relations Principal"
      },
      {
        "name": "Joana Silva",
        "role": "Managing Director"
      },
      {
        "name": "Nuno Almeida",
        "role": "Chief Compliance Officer"
      }
    ]
  },
  {
    "id": 67,
    "slug": "harbor-horizon-trust",
    "companyName": "Harbor Horizon Trust",
    "licenseNumber": "CV-BOA-2020-0067",
    "issueDate": "2020-07-15",
    "expiryDate": "2025-07-15",
    "status": "Active",
    "registeredAddress": "78 Rabil Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@harbor-horizon-trust.cv",
    "contactPhone": "+238 59858 662",
    "businessCategory": "Wealth Management Services",
    "complianceNotes": "Completed independent AML/CTF audit with satisfactory findings.",
    "description": "Founded in 2020, Harbor Horizon Trust implements disciplined risk management tailored to maritime shipping clients.",
    "keyPersons": [
      {
        "name": "Helena Pereira",
        "role": "Managing Director"
      },
      {
        "name": "Luis Vidal",
        "role": "Chief Compliance Officer"
      }
    ]
  },
  {
    "id": 68,
    "slug": "mariner-horizon-associates",
    "companyName": "Mariner Horizon Associates",
    "licenseNumber": "CV-BOA-2021-0068",
    "issueDate": "2021-10-22",
    "expiryDate": "2026-10-22",
    "status": "Under Review",
    "registeredAddress": "79 Sal Rei Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@mariner-horizon-associates.cv",
    "contactPhone": "+238 59871 669",
    "businessCategory": "Payment and Remittance Services",
    "complianceNotes": "Subject to annual prudential assessment focusing on liquidity buffers.",
    "description": "Founded in 2021, Mariner Horizon Associates provides onboarding support for fintech entrants expanding into Lusophone markets.",
    "keyPersons": [
      {
        "name": "Igor Ramos",
        "role": "Chief Compliance Officer"
      },
      {
        "name": "Marta Zamora",
        "role": "Head of Trading"
      },
      {
        "name": "Paulo Esteves",
        "role": "Risk Management Lead"
      }
    ]
  },
  {
    "id": 69,
    "slug": "palm-horizon-investments",
    "companyName": "Palm Horizon Investments",
    "licenseNumber": "CV-BOA-2022-0069",
    "issueDate": "2022-01-01",
    "expiryDate": "2027-01-01",
    "status": "Suspended",
    "registeredAddress": "80 Bofareira Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@palm-horizon-investments.cv",
    "contactPhone": "+238 59884 676",
    "businessCategory": "Treasury Outsourcing",
    "complianceNotes": "Maintains bilingual client disclosures in Portuguese and English.",
    "description": "Founded in 2022, Palm Horizon Investments operates bespoke FX solutions for renewable energy initiatives throughout Boa Vista.",
    "keyPersons": [
      {
        "name": "Joana Tavares",
        "role": "Head of Trading"
      },
      {
        "name": "Nuno Barbosa",
        "role": "Risk Management Lead"
      }
    ]
  },
  {
    "id": 70,
    "slug": "sand-horizon-services",
    "companyName": "Sand Horizon Services",
    "licenseNumber": "CV-BOA-2023-0070",
    "issueDate": "2023-04-08",
    "expiryDate": "2028-04-08",
    "status": "Lapsed",
    "registeredAddress": "81 Estância de Baixo Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@sand-horizon-services.cv",
    "contactPhone": "+238 59897 683",
    "businessCategory": "Corporate FX Risk Advisory",
    "complianceNotes": "Operates under conditional approval pending technology platform migration.",
    "description": "Founded in 2023, Sand Horizon Services maintains correspondent networks facilitating cross-border commodity trades.",
    "keyPersons": [
      {
        "name": "Luis Xavier",
        "role": "Risk Management Lead"
      },
      {
        "name": "Olivia Delgado",
        "role": "Operations Supervisor"
      },
      {
        "name": "Sergio Lima",
        "role": "Client Relations Principal"
      }
    ]
  },
  {
    "id": 71,
    "slug": "atlantic-ledger-advisors",
    "companyName": "Atlantic Ledger Advisors",
    "licenseNumber": "CV-BOA-2014-0071",
    "issueDate": "2014-07-15",
    "expiryDate": "N/A",
    "status": "Active",
    "registeredAddress": "82 Povoação Velha Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@atlantic-ledger-advisors.cv",
    "contactPhone": "+238 59910 690",
    "businessCategory": "Retail FX Brokerage",
    "complianceNotes": "Maintains quarterly compliance updates with the Boa Vista Financial Authority.",
    "description": "Founded in 2014, Atlantic Ledger Advisors delivers currency execution and settlement solutions to the Cape Verdean hospitality and tourism sector.",
    "keyPersons": [
      {
        "name": "Marta Almeida",
        "role": "Operations Supervisor"
      },
      {
        "name": "Paulo Fernandes",
        "role": "Client Relations Principal"
      }
    ]
  },
  {
    "id": 72,
    "slug": "azure-ledger-holdings",
    "companyName": "Azure Ledger Holdings",
    "licenseNumber": "CV-BOA-2015-0072",
    "issueDate": "2015-10-22",
    "expiryDate": "2020-10-22",
    "status": "Active",
    "registeredAddress": "83 Rabil Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@azure-ledger-holdings.cv",
    "contactPhone": "+238 59923 697",
    "businessCategory": "Institutional FX Brokerage",
    "complianceNotes": "Underwent enhanced due diligence during the most recent supervisory cycle.",
    "description": "Founded in 2015, Azure Ledger Holdings supports regional exporters with hedging strategies against Euro and USD volatility.",
    "keyPersons": [
      {
        "name": "Nuno Cardoso",
        "role": "Client Relations Principal"
      },
      {
        "name": "Rita Henriques",
        "role": "Managing Director"
      },
      {
        "name": "Vasco Pereira",
        "role": "Chief Compliance Officer"
      }
    ]
  },
  {
    "id": 73,
    "slug": "beacon-ledger-partners",
    "companyName": "Beacon Ledger Partners",
    "licenseNumber": "CV-BOA-2016-0073",
    "issueDate": "2016-01-01",
    "expiryDate": "2021-01-01",
    "status": "Active",
    "registeredAddress": "84 Sal Rei Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@beacon-ledger-partners.cv",
    "contactPhone": "+238 59936 704",
    "businessCategory": "Multi-Asset Dealing Desk",
    "complianceNotes": "Submitted revised capital adequacy statement in the last reporting period.",
    "description": "Founded in 2016, Beacon Ledger Partners specialises in low-latency order routing for diaspora remittance channels.",
    "keyPersons": [
      {
        "name": "Olivia Esteves",
        "role": "Managing Director"
      },
      {
        "name": "Sergio Macedo",
        "role": "Chief Compliance Officer"
      }
    ]
  },
  {
    "id": 74,
    "slug": "blue-ledger-ventures",
    "companyName": "Blue Ledger Ventures",
    "licenseNumber": "CV-BOA-2017-0074",
    "issueDate": "2017-04-08",
    "expiryDate": "2022-04-08",
    "status": "Active",
    "registeredAddress": "85 Bofareira Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@blue-ledger-ventures.cv",
    "contactPhone": "+238 59949 711",
    "businessCategory": "FX Liquidity Provision",
    "complianceNotes": "Implements mandatory client asset segregation with monthly reconciliations.",
    "description": "Founded in 2017, Blue Ledger Ventures partners with local banks to provide treasury outsourcing and liquidity management.",
    "keyPersons": [
      {
        "name": "Paulo Gomes",
        "role": "Chief Compliance Officer"
      },
      {
        "name": "Teresa Oliveira",
        "role": "Head of Trading"
      },
      {
        "name": "Yuri Tavares",
        "role": "Risk Management Lead"
      }
    ]
  },
  {
    "id": 75,
    "slug": "coral-ledger-consulting",
    "companyName": "Coral Ledger Consulting",
    "licenseNumber": "CV-BOA-2018-0075",
    "issueDate": "2018-07-15",
    "expiryDate": "2023-07-15",
    "status": "Under Review",
    "registeredAddress": "86 Estância de Baixo Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@coral-ledger-consulting.cv",
    "contactPhone": "+238 59962 718",
    "businessCategory": "Commodities Brokerage",
    "complianceNotes": "Participates in cross-border information sharing with Lusophone regulators.",
    "description": "Founded in 2018, Coral Ledger Consulting offers portfolio diversification tools for high-net-worth investors across West Africa.",
    "keyPersons": [
      {
        "name": "Rita Lima",
        "role": "Head of Trading"
      },
      {
        "name": "Vasco Quintino",
        "role": "Risk Management Lead"
      }
    ]
  },
  {
    "id": 76,
    "slug": "emerald-ledger-markets",
    "companyName": "Emerald Ledger Markets",
    "licenseNumber": "CV-BOA-2019-0076",
    "issueDate": "2019-10-22",
    "expiryDate": "2024-10-22",
    "status": "Suspended",
    "registeredAddress": "87 Povoação Velha Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@emerald-ledger-markets.cv",
    "contactPhone": "+238 59975 725",
    "businessCategory": "Derivatives Advisory",
    "complianceNotes": "Filed updated disaster recovery plan incorporating offshore redundancy.",
    "description": "Founded in 2019, Emerald Ledger Markets focuses on sustainable finance instruments linked to island infrastructure projects.",
    "keyPersons": [
      {
        "name": "Sergio Neves",
        "role": "Risk Management Lead"
      },
      {
        "name": "Wilma Silva",
        "role": "Operations Supervisor"
      },
      {
        "name": "Bruno Almeida",
        "role": "Client Relations Principal"
      }
    ]
  },
  {
    "id": 77,
    "slug": "harbor-ledger-trust",
    "companyName": "Harbor Ledger Trust",
    "licenseNumber": "CV-BOA-2020-0077",
    "issueDate": "2020-01-01",
    "expiryDate": "2025-01-01",
    "status": "Lapsed",
    "registeredAddress": "88 Rabil Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@harbor-ledger-trust.cv",
    "contactPhone": "+238 59988 732",
    "businessCategory": "Wealth Management Services",
    "complianceNotes": "Completed independent AML/CTF audit with satisfactory findings.",
    "description": "Founded in 2020, Harbor Ledger Trust implements disciplined risk management tailored to maritime shipping clients.",
    "keyPersons": [
      {
        "name": "Teresa Pereira",
        "role": "Operations Supervisor"
      },
      {
        "name": "Yuri Vidal",
        "role": "Client Relations Principal"
      }
    ]
  },
  {
    "id": 78,
    "slug": "mariner-ledger-associates",
    "companyName": "Mariner Ledger Associates",
    "licenseNumber": "CV-BOA-2021-0078",
    "issueDate": "2021-04-08",
    "expiryDate": "N/A",
    "status": "Active",
    "registeredAddress": "89 Sal Rei Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@mariner-ledger-associates.cv",
    "contactPhone": "+238 59001 739",
    "businessCategory": "Payment and Remittance Services",
    "complianceNotes": "Subject to annual prudential assessment focusing on liquidity buffers.",
    "description": "Founded in 2021, Mariner Ledger Associates provides onboarding support for fintech entrants expanding into Lusophone markets.",
    "keyPersons": [
      {
        "name": "Vasco Ramos",
        "role": "Client Relations Principal"
      },
      {
        "name": "Ana Zamora",
        "role": "Managing Director"
      },
      {
        "name": "Daniel Esteves",
        "role": "Chief Compliance Officer"
      }
    ]
  },
  {
    "id": 79,
    "slug": "palm-ledger-investments",
    "companyName": "Palm Ledger Investments",
    "licenseNumber": "CV-BOA-2022-0079",
    "issueDate": "2022-07-15",
    "expiryDate": "2027-07-15",
    "status": "Active",
    "registeredAddress": "90 Bofareira Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@palm-ledger-investments.cv",
    "contactPhone": "+238 59014 746",
    "businessCategory": "Treasury Outsourcing",
    "complianceNotes": "Maintains bilingual client disclosures in Portuguese and English.",
    "description": "Founded in 2022, Palm Ledger Investments operates bespoke FX solutions for renewable energy initiatives throughout Boa Vista.",
    "keyPersons": [
      {
        "name": "Wilma Tavares",
        "role": "Managing Director"
      },
      {
        "name": "Bruno Barbosa",
        "role": "Chief Compliance Officer"
      }
    ]
  },
  {
    "id": 80,
    "slug": "sand-ledger-services",
    "companyName": "Sand Ledger Services",
    "licenseNumber": "CV-BOA-2023-0080",
    "issueDate": "2023-10-22",
    "expiryDate": "2028-10-22",
    "status": "Active",
    "registeredAddress": "91 Estância de Baixo Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@sand-ledger-services.cv",
    "contactPhone": "+238 59027 753",
    "businessCategory": "Corporate FX Risk Advisory",
    "complianceNotes": "Operates under conditional approval pending technology platform migration.",
    "description": "Founded in 2023, Sand Ledger Services maintains correspondent networks facilitating cross-border commodity trades.",
    "keyPersons": [
      {
        "name": "Yuri Xavier",
        "role": "Chief Compliance Officer"
      },
      {
        "name": "Carla Delgado",
        "role": "Head of Trading"
      },
      {
        "name": "Fabio Lima",
        "role": "Risk Management Lead"
      }
    ]
  },
  {
    "id": 81,
    "slug": "atlantic-maritime-advisors",
    "companyName": "Atlantic Maritime Advisors",
    "licenseNumber": "CV-BOA-2014-0081",
    "issueDate": "2014-01-01",
    "expiryDate": "2019-01-01",
    "status": "Active",
    "registeredAddress": "92 Povoação Velha Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@atlantic-maritime-advisors.cv",
    "contactPhone": "+238 59040 760",
    "businessCategory": "Retail FX Brokerage",
    "complianceNotes": "Maintains quarterly compliance updates with the Boa Vista Financial Authority.",
    "description": "Founded in 2014, Atlantic Maritime Advisors delivers currency execution and settlement solutions to the Cape Verdean hospitality and tourism sector.",
    "keyPersons": [
      {
        "name": "Ana Almeida",
        "role": "Head of Trading"
      },
      {
        "name": "Daniel Fernandes",
        "role": "Risk Management Lead"
      }
    ]
  },
  {
    "id": 82,
    "slug": "azure-maritime-holdings",
    "companyName": "Azure Maritime Holdings",
    "licenseNumber": "CV-BOA-2015-0082",
    "issueDate": "2015-04-08",
    "expiryDate": "2020-04-08",
    "status": "Under Review",
    "registeredAddress": "93 Rabil Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@azure-maritime-holdings.cv",
    "contactPhone": "+238 59053 767",
    "businessCategory": "Institutional FX Brokerage",
    "complianceNotes": "Underwent enhanced due diligence during the most recent supervisory cycle.",
    "description": "Founded in 2015, Azure Maritime Holdings supports regional exporters with hedging strategies against Euro and USD volatility.",
    "keyPersons": [
      {
        "name": "Bruno Cardoso",
        "role": "Risk Management Lead"
      },
      {
        "name": "Elisa Henriques",
        "role": "Operations Supervisor"
      },
      {
        "name": "Igor Pereira",
        "role": "Client Relations Principal"
      }
    ]
  },
  {
    "id": 83,
    "slug": "beacon-maritime-partners",
    "companyName": "Beacon Maritime Partners",
    "licenseNumber": "CV-BOA-2016-0083",
    "issueDate": "2016-07-15",
    "expiryDate": "2021-07-15",
    "status": "Suspended",
    "registeredAddress": "94 Sal Rei Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@beacon-maritime-partners.cv",
    "contactPhone": "+238 59066 774",
    "businessCategory": "Multi-Asset Dealing Desk",
    "complianceNotes": "Submitted revised capital adequacy statement in the last reporting period.",
    "description": "Founded in 2016, Beacon Maritime Partners specialises in low-latency order routing for diaspora remittance channels.",
    "keyPersons": [
      {
        "name": "Carla Esteves",
        "role": "Operations Supervisor"
      },
      {
        "name": "Fabio Macedo",
        "role": "Client Relations Principal"
      }
    ]
  },
  {
    "id": 84,
    "slug": "blue-maritime-ventures",
    "companyName": "Blue Maritime Ventures",
    "licenseNumber": "CV-BOA-2017-0084",
    "issueDate": "2017-10-22",
    "expiryDate": "2022-10-22",
    "status": "Lapsed",
    "registeredAddress": "95 Bofareira Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@blue-maritime-ventures.cv",
    "contactPhone": "+238 59079 781",
    "businessCategory": "FX Liquidity Provision",
    "complianceNotes": "Implements mandatory client asset segregation with monthly reconciliations.",
    "description": "Founded in 2017, Blue Maritime Ventures partners with local banks to provide treasury outsourcing and liquidity management.",
    "keyPersons": [
      {
        "name": "Daniel Gomes",
        "role": "Client Relations Principal"
      },
      {
        "name": "Helena Oliveira",
        "role": "Managing Director"
      },
      {
        "name": "Luis Tavares",
        "role": "Chief Compliance Officer"
      }
    ]
  },
  {
    "id": 85,
    "slug": "coral-maritime-consulting",
    "companyName": "Coral Maritime Consulting",
    "licenseNumber": "CV-BOA-2018-0085",
    "issueDate": "2018-01-01",
    "expiryDate": "N/A",
    "status": "Active",
    "registeredAddress": "96 Estância de Baixo Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@coral-maritime-consulting.cv",
    "contactPhone": "+238 59092 788",
    "businessCategory": "Commodities Brokerage",
    "complianceNotes": "Participates in cross-border information sharing with Lusophone regulators.",
    "description": "Founded in 2018, Coral Maritime Consulting offers portfolio diversification tools for high-net-worth investors across West Africa.",
    "keyPersons": [
      {
        "name": "Elisa Lima",
        "role": "Managing Director"
      },
      {
        "name": "Igor Quintino",
        "role": "Chief Compliance Officer"
      }
    ]
  },
  {
    "id": 86,
    "slug": "emerald-maritime-markets",
    "companyName": "Emerald Maritime Markets",
    "licenseNumber": "CV-BOA-2019-0086",
    "issueDate": "2019-04-08",
    "expiryDate": "2024-04-08",
    "status": "Active",
    "registeredAddress": "97 Povoação Velha Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@emerald-maritime-markets.cv",
    "contactPhone": "+238 59105 795",
    "businessCategory": "Derivatives Advisory",
    "complianceNotes": "Filed updated disaster recovery plan incorporating offshore redundancy.",
    "description": "Founded in 2019, Emerald Maritime Markets focuses on sustainable finance instruments linked to island infrastructure projects.",
    "keyPersons": [
      {
        "name": "Fabio Neves",
        "role": "Chief Compliance Officer"
      },
      {
        "name": "Joana Silva",
        "role": "Head of Trading"
      },
      {
        "name": "Nuno Almeida",
        "role": "Risk Management Lead"
      }
    ]
  },
  {
    "id": 87,
    "slug": "harbor-maritime-trust",
    "companyName": "Harbor Maritime Trust",
    "licenseNumber": "CV-BOA-2020-0087",
    "issueDate": "2020-07-15",
    "expiryDate": "2025-07-15",
    "status": "Active",
    "registeredAddress": "98 Rabil Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@harbor-maritime-trust.cv",
    "contactPhone": "+238 59118 802",
    "businessCategory": "Wealth Management Services",
    "complianceNotes": "Completed independent AML/CTF audit with satisfactory findings.",
    "description": "Founded in 2020, Harbor Maritime Trust implements disciplined risk management tailored to maritime shipping clients.",
    "keyPersons": [
      {
        "name": "Helena Pereira",
        "role": "Head of Trading"
      },
      {
        "name": "Luis Vidal",
        "role": "Risk Management Lead"
      }
    ]
  },
  {
    "id": 88,
    "slug": "mariner-maritime-associates",
    "companyName": "Mariner Maritime Associates",
    "licenseNumber": "CV-BOA-2021-0088",
    "issueDate": "2021-10-22",
    "expiryDate": "2026-10-22",
    "status": "Active",
    "registeredAddress": "99 Sal Rei Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@mariner-maritime-associates.cv",
    "contactPhone": "+238 59131 809",
    "businessCategory": "Payment and Remittance Services",
    "complianceNotes": "Subject to annual prudential assessment focusing on liquidity buffers.",
    "description": "Founded in 2021, Mariner Maritime Associates provides onboarding support for fintech entrants expanding into Lusophone markets.",
    "keyPersons": [
      {
        "name": "Igor Ramos",
        "role": "Risk Management Lead"
      },
      {
        "name": "Marta Zamora",
        "role": "Operations Supervisor"
      },
      {
        "name": "Paulo Esteves",
        "role": "Client Relations Principal"
      }
    ]
  },
  {
    "id": 89,
    "slug": "palm-maritime-investments",
    "companyName": "Palm Maritime Investments",
    "licenseNumber": "CV-BOA-2022-0089",
    "issueDate": "2022-01-01",
    "expiryDate": "2027-01-01",
    "status": "Under Review",
    "registeredAddress": "100 Bofareira Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@palm-maritime-investments.cv",
    "contactPhone": "+238 59144 816",
    "businessCategory": "Treasury Outsourcing",
    "complianceNotes": "Maintains bilingual client disclosures in Portuguese and English.",
    "description": "Founded in 2022, Palm Maritime Investments operates bespoke FX solutions for renewable energy initiatives throughout Boa Vista.",
    "keyPersons": [
      {
        "name": "Joana Tavares",
        "role": "Operations Supervisor"
      },
      {
        "name": "Nuno Barbosa",
        "role": "Client Relations Principal"
      }
    ]
  },
  {
    "id": 90,
    "slug": "sand-maritime-services",
    "companyName": "Sand Maritime Services",
    "licenseNumber": "CV-BOA-2023-0090",
    "issueDate": "2023-04-08",
    "expiryDate": "2028-04-08",
    "status": "Suspended",
    "registeredAddress": "101 Estância de Baixo Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@sand-maritime-services.cv",
    "contactPhone": "+238 59157 823",
    "businessCategory": "Corporate FX Risk Advisory",
    "complianceNotes": "Operates under conditional approval pending technology platform migration.",
    "description": "Founded in 2023, Sand Maritime Services maintains correspondent networks facilitating cross-border commodity trades.",
    "keyPersons": [
      {
        "name": "Luis Xavier",
        "role": "Client Relations Principal"
      },
      {
        "name": "Olivia Delgado",
        "role": "Managing Director"
      },
      {
        "name": "Sergio Lima",
        "role": "Chief Compliance Officer"
      }
    ]
  },
  {
    "id": 91,
    "slug": "atlantic-summit-advisors",
    "companyName": "Atlantic Summit Advisors",
    "licenseNumber": "CV-BOA-2014-0091",
    "issueDate": "2014-07-15",
    "expiryDate": "2019-07-15",
    "status": "Lapsed",
    "registeredAddress": "102 Povoação Velha Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@atlantic-summit-advisors.cv",
    "contactPhone": "+238 59170 830",
    "businessCategory": "Retail FX Brokerage",
    "complianceNotes": "Maintains quarterly compliance updates with the Boa Vista Financial Authority.",
    "description": "Founded in 2014, Atlantic Summit Advisors delivers currency execution and settlement solutions to the Cape Verdean hospitality and tourism sector.",
    "keyPersons": [
      {
        "name": "Marta Almeida",
        "role": "Managing Director"
      },
      {
        "name": "Paulo Fernandes",
        "role": "Chief Compliance Officer"
      }
    ]
  },
  {
    "id": 92,
    "slug": "azure-summit-holdings",
    "companyName": "Azure Summit Holdings",
    "licenseNumber": "CV-BOA-2015-0092",
    "issueDate": "2015-10-22",
    "expiryDate": "N/A",
    "status": "Active",
    "registeredAddress": "103 Rabil Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@azure-summit-holdings.cv",
    "contactPhone": "+238 59183 837",
    "businessCategory": "Institutional FX Brokerage",
    "complianceNotes": "Underwent enhanced due diligence during the most recent supervisory cycle.",
    "description": "Founded in 2015, Azure Summit Holdings supports regional exporters with hedging strategies against Euro and USD volatility.",
    "keyPersons": [
      {
        "name": "Nuno Cardoso",
        "role": "Chief Compliance Officer"
      },
      {
        "name": "Rita Henriques",
        "role": "Head of Trading"
      },
      {
        "name": "Vasco Pereira",
        "role": "Risk Management Lead"
      }
    ]
  },
  {
    "id": 93,
    "slug": "beacon-summit-partners",
    "companyName": "Beacon Summit Partners",
    "licenseNumber": "CV-BOA-2016-0093",
    "issueDate": "2016-01-01",
    "expiryDate": "2021-01-01",
    "status": "Active",
    "registeredAddress": "104 Sal Rei Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@beacon-summit-partners.cv",
    "contactPhone": "+238 59196 844",
    "businessCategory": "Multi-Asset Dealing Desk",
    "complianceNotes": "Submitted revised capital adequacy statement in the last reporting period.",
    "description": "Founded in 2016, Beacon Summit Partners specialises in low-latency order routing for diaspora remittance channels.",
    "keyPersons": [
      {
        "name": "Olivia Esteves",
        "role": "Head of Trading"
      },
      {
        "name": "Sergio Macedo",
        "role": "Risk Management Lead"
      }
    ]
  },
  {
    "id": 94,
    "slug": "blue-summit-ventures",
    "companyName": "Blue Summit Ventures",
    "licenseNumber": "CV-BOA-2017-0094",
    "issueDate": "2017-04-08",
    "expiryDate": "2022-04-08",
    "status": "Active",
    "registeredAddress": "105 Bofareira Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@blue-summit-ventures.cv",
    "contactPhone": "+238 59209 851",
    "businessCategory": "FX Liquidity Provision",
    "complianceNotes": "Implements mandatory client asset segregation with monthly reconciliations.",
    "description": "Founded in 2017, Blue Summit Ventures partners with local banks to provide treasury outsourcing and liquidity management.",
    "keyPersons": [
      {
        "name": "Paulo Gomes",
        "role": "Risk Management Lead"
      },
      {
        "name": "Teresa Oliveira",
        "role": "Operations Supervisor"
      },
      {
        "name": "Yuri Tavares",
        "role": "Client Relations Principal"
      }
    ]
  },
  {
    "id": 95,
    "slug": "coral-summit-consulting",
    "companyName": "Coral Summit Consulting",
    "licenseNumber": "CV-BOA-2018-0095",
    "issueDate": "2018-07-15",
    "expiryDate": "2023-07-15",
    "status": "Active",
    "registeredAddress": "106 Estância de Baixo Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@coral-summit-consulting.cv",
    "contactPhone": "+238 59222 858",
    "businessCategory": "Commodities Brokerage",
    "complianceNotes": "Participates in cross-border information sharing with Lusophone regulators.",
    "description": "Founded in 2018, Coral Summit Consulting offers portfolio diversification tools for high-net-worth investors across West Africa.",
    "keyPersons": [
      {
        "name": "Rita Lima",
        "role": "Operations Supervisor"
      },
      {
        "name": "Vasco Quintino",
        "role": "Client Relations Principal"
      }
    ]
  },
  {
    "id": 96,
    "slug": "emerald-summit-markets",
    "companyName": "Emerald Summit Markets",
    "licenseNumber": "CV-BOA-2019-0096",
    "issueDate": "2019-10-22",
    "expiryDate": "2024-10-22",
    "status": "Under Review",
    "registeredAddress": "107 Povoação Velha Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@emerald-summit-markets.cv",
    "contactPhone": "+238 59235 865",
    "businessCategory": "Derivatives Advisory",
    "complianceNotes": "Filed updated disaster recovery plan incorporating offshore redundancy.",
    "description": "Founded in 2019, Emerald Summit Markets focuses on sustainable finance instruments linked to island infrastructure projects.",
    "keyPersons": [
      {
        "name": "Sergio Neves",
        "role": "Client Relations Principal"
      },
      {
        "name": "Wilma Silva",
        "role": "Managing Director"
      },
      {
        "name": "Bruno Almeida",
        "role": "Chief Compliance Officer"
      }
    ]
  },
  {
    "id": 97,
    "slug": "harbor-summit-trust",
    "companyName": "Harbor Summit Trust",
    "licenseNumber": "CV-BOA-2020-0097",
    "issueDate": "2020-01-01",
    "expiryDate": "2025-01-01",
    "status": "Suspended",
    "registeredAddress": "108 Rabil Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@harbor-summit-trust.cv",
    "contactPhone": "+238 59248 872",
    "businessCategory": "Wealth Management Services",
    "complianceNotes": "Completed independent AML/CTF audit with satisfactory findings.",
    "description": "Founded in 2020, Harbor Summit Trust implements disciplined risk management tailored to maritime shipping clients.",
    "keyPersons": [
      {
        "name": "Teresa Pereira",
        "role": "Managing Director"
      },
      {
        "name": "Yuri Vidal",
        "role": "Chief Compliance Officer"
      }
    ]
  },
  {
    "id": 98,
    "slug": "mariner-summit-associates",
    "companyName": "Mariner Summit Associates",
    "licenseNumber": "CV-BOA-2021-0098",
    "issueDate": "2021-04-08",
    "expiryDate": "2026-04-08",
    "status": "Lapsed",
    "registeredAddress": "109 Sal Rei Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@mariner-summit-associates.cv",
    "contactPhone": "+238 59261 879",
    "businessCategory": "Payment and Remittance Services",
    "complianceNotes": "Subject to annual prudential assessment focusing on liquidity buffers.",
    "description": "Founded in 2021, Mariner Summit Associates provides onboarding support for fintech entrants expanding into Lusophone markets.",
    "keyPersons": [
      {
        "name": "Vasco Ramos",
        "role": "Chief Compliance Officer"
      },
      {
        "name": "Ana Zamora",
        "role": "Head of Trading"
      },
      {
        "name": "Daniel Esteves",
        "role": "Risk Management Lead"
      }
    ]
  },
  {
    "id": 99,
    "slug": "palm-summit-investments",
    "companyName": "Palm Summit Investments",
    "licenseNumber": "CV-BOA-2022-0099",
    "issueDate": "2022-07-15",
    "expiryDate": "N/A",
    "status": "Active",
    "registeredAddress": "110 Bofareira Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@palm-summit-investments.cv",
    "contactPhone": "+238 59274 886",
    "businessCategory": "Treasury Outsourcing",
    "complianceNotes": "Maintains bilingual client disclosures in Portuguese and English.",
    "description": "Founded in 2022, Palm Summit Investments operates bespoke FX solutions for renewable energy initiatives throughout Boa Vista.",
    "keyPersons": [
      {
        "name": "Wilma Tavares",
        "role": "Head of Trading"
      },
      {
        "name": "Bruno Barbosa",
        "role": "Risk Management Lead"
      }
    ]
  },
  {
    "id": 100,
    "slug": "sand-summit-services",
    "companyName": "Sand Summit Services",
    "licenseNumber": "CV-BOA-2023-0100",
    "issueDate": "2023-10-22",
    "expiryDate": "2028-10-22",
    "status": "Active",
    "registeredAddress": "111 Estância de Baixo Coastal Road, Boa Vista, Cabo Verde",
    "contactEmail": "licensing@sand-summit-services.cv",
    "contactPhone": "+238 59287 893",
    "businessCategory": "Corporate FX Risk Advisory",
    "complianceNotes": "Operates under conditional approval pending technology platform migration.",
    "description": "Founded in 2023, Sand Summit Services maintains correspondent networks facilitating cross-border commodity trades.",
    "keyPersons": [
      {
        "name": "Yuri Xavier",
        "role": "Risk Management Lead"
      },
      {
        "name": "Carla Delgado",
        "role": "Operations Supervisor"
      },
      {
        "name": "Fabio Lima",
        "role": "Client Relations Principal"
      }
    ]
  }
] satisfies LicenseRecord[];

export function getLicenseBySlug(slug: string) {
  return licenses.find((entry) => entry.slug === slug);
}

export function searchLicenses(query: string) {
  const normalized = query.trim().toLowerCase();
  if (!normalized) return licenses;
  return licenses.filter((entry) => {
    return (
      entry.companyName.toLowerCase().includes(normalized) ||
      entry.licenseNumber.toLowerCase().includes(normalized) ||
      entry.businessCategory.toLowerCase().includes(normalized) ||
      entry.description.toLowerCase().includes(normalized)
    );
  });
}
