// Auto-generated by scripts/generate-licenses.mjs
// Do not edit directly. Update the generator if changes are required.

export interface LicenseRecord {
  id: number;
  slug: string;
  companyName: string;
  licenseNumber: string;
  issueDate: string;
  expiryDate: string;
  status: string;
  registeredAddress: string;
  contactEmail: string;
  contactPhone: string;
  businessCategory: string;
  complianceNotes: string;
  description: string;
  keyPersons: { name: string; role: string }[];
}

export const licenses = [
  {
    "id": 1,
    "slug": "atlantic-bridge-advisors",
    "companyName": "Atlantic Bridge Advisors",
    "licenseNumber": "BVP-FX-14Q1-NPC5-DW",
    "issueDate": "2014-01-01",
    "expiryDate": "N/A",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@atlantic-bridge-advisors.cv",
    "contactPhone": "",
    "businessCategory": "Retail FX Brokerage",
    "complianceNotes": "Maintains quarterly compliance updates with the Boa Vista Financial Authority.",
    "description": "Founded in 2014, Atlantic Bridge Advisors delivers currency execution and settlement solutions to the Cape Verdean hospitality and tourism sector.",
    "keyPersons": [
      {
        "name": "Joana Ramos",
        "role": "Treasury Controller"
      },
      {
        "name": "Marta Oliveira",
        "role": "Head of Trading"
      }
    ]
  },
  {
    "id": 2,
    "slug": "azure-bridge-holdings",
    "companyName": "Azure Bridge Holdings",
    "licenseNumber": "BVP-IX-15Q2-HEF4-AF",
    "issueDate": "2015-04-08",
    "expiryDate": "2020-04-08",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@azure-bridge-holdings.cv",
    "contactPhone": "",
    "businessCategory": "Institutional FX Brokerage",
    "complianceNotes": "Underwent enhanced due diligence during the most recent supervisory cycle.",
    "description": "Founded in 2015, Azure Bridge Holdings supports regional exporters with hedging strategies against Euro and USD volatility.",
    "keyPersons": [
      {
        "name": "Vasco Macedo",
        "role": "Head of Trading"
      },
      {
        "name": "Bruno Delgado",
        "role": "Operations Supervisor"
      }
    ]
  },
  {
    "id": 3,
    "slug": "beacon-bridge-partners",
    "companyName": "Beacon Bridge Partners",
    "licenseNumber": "BVP-MD-16Q3-C5J3-7Z",
    "issueDate": "2016-07-15",
    "expiryDate": "2021-07-15",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@beacon-bridge-partners.cv",
    "contactPhone": "",
    "businessCategory": "Multi-Asset Dealing Desk",
    "complianceNotes": "Submitted revised capital adequacy statement in the last reporting period.",
    "description": "Founded in 2016, Beacon Bridge Partners specialises in low-latency order routing for diaspora remittance channels.",
    "keyPersons": [
      {
        "name": "Helena Esteves",
        "role": "Institutional Liaison"
      },
      {
        "name": "Nuno Ramos",
        "role": "Treasury Controller"
      }
    ]
  },
  {
    "id": 4,
    "slug": "blue-bridge-ventures",
    "companyName": "Blue Bridge Ventures",
    "licenseNumber": "BVP-LP-17Q4-7UM2-ZF",
    "issueDate": "2017-10-22",
    "expiryDate": "2022-10-22",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@blue-bridge-ventures.cv",
    "contactPhone": "",
    "businessCategory": "FX Liquidity Provision",
    "complianceNotes": "Implements mandatory client asset segregation with monthly reconciliations.",
    "description": "Founded in 2017, Blue Bridge Ventures partners with local banks to provide treasury outsourcing and liquidity management.",
    "keyPersons": [
      {
        "name": "Sergio Zamora",
        "role": "Client Relations Principal"
      },
      {
        "name": "Carla Gomes",
        "role": "Market Surveillance Officer"
      }
    ]
  },
  {
    "id": 5,
    "slug": "coral-bridge-consulting",
    "companyName": "Coral Bridge Consulting",
    "licenseNumber": "BVP-CB-18Q1-2KQZ-NY",
    "issueDate": "2018-01-01",
    "expiryDate": "2023-01-01",
    "status": "Under Review",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@coral-bridge-consulting.cv",
    "contactPhone": "",
    "businessCategory": "Commodities Brokerage",
    "complianceNotes": "Participates in cross-border information sharing with Lusophone regulators.",
    "description": "Founded in 2018, Coral Bridge Consulting offers portfolio diversification tools for high-net-worth investors across West Africa.",
    "keyPersons": [
      {
        "name": "Daniel Ramos",
        "role": "Chief Compliance Officer"
      },
      {
        "name": "Paulo Vidal",
        "role": "Settlement Supervisor"
      },
      {
        "name": "Paulo Macedo",
        "role": "Chief Compliance Officer"
      }
    ]
  },
  {
    "id": 6,
    "slug": "emerald-bridge-markets",
    "companyName": "Emerald Bridge Markets",
    "licenseNumber": "BVP-DA-19Q2-VATY-JH",
    "issueDate": "2019-04-08",
    "expiryDate": "2024-04-08",
    "status": "Suspended",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@emerald-bridge-markets.cv",
    "contactPhone": "",
    "businessCategory": "Derivatives Advisory",
    "complianceNotes": "Filed updated disaster recovery plan incorporating offshore redundancy.",
    "description": "Founded in 2019, Emerald Bridge Markets focuses on sustainable finance instruments linked to island infrastructure projects.",
    "keyPersons": [
      {
        "name": "Olivia Macedo",
        "role": "AML Programme Lead"
      },
      {
        "name": "Daniel Macedo",
        "role": "Head of Trading"
      },
      {
        "name": "Igor Delgado",
        "role": "Chief Compliance Officer"
      }
    ]
  },
  {
    "id": 7,
    "slug": "harbor-bridge-trust",
    "companyName": "Harbor Bridge Trust",
    "licenseNumber": "BVP-WM-20Q3-QZWX-F3",
    "issueDate": "2020-07-15",
    "expiryDate": "2025-07-15",
    "status": "Lapsed",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@harbor-bridge-trust.cv",
    "contactPhone": "",
    "businessCategory": "Wealth Management Services",
    "complianceNotes": "Completed independent AML/CTF audit with satisfactory findings.",
    "description": "Founded in 2020, Harbor Bridge Trust implements disciplined risk management tailored to maritime shipping clients.",
    "keyPersons": [
      {
        "name": "Bruno Esteves",
        "role": "Risk Management Lead"
      },
      {
        "name": "Rita Almeida",
        "role": "Operations Supervisor"
      },
      {
        "name": "Carla Vidal",
        "role": "Chief Compliance Officer"
      }
    ]
  },
  {
    "id": 8,
    "slug": "mariner-bridge-associates",
    "companyName": "Mariner Bridge Associates",
    "licenseNumber": "BVP-PR-21Q4-KQZW-CM",
    "issueDate": "2021-10-22",
    "expiryDate": "N/A",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@mariner-bridge-associates.cv",
    "contactPhone": "",
    "businessCategory": "Payment and Remittance Services",
    "complianceNotes": "Subject to annual prudential assessment focusing on liquidity buffers.",
    "description": "Founded in 2021, Mariner Bridge Associates provides onboarding support for fintech entrants expanding into Lusophone markets.",
    "keyPersons": [
      {
        "name": "Marta Zamora",
        "role": "Settlement Supervisor"
      },
      {
        "name": "Fabio Pereira",
        "role": "Treasury Controller"
      },
      {
        "name": "Teresa Oliveira",
        "role": "Head of Trading"
      }
    ]
  },
  {
    "id": 9,
    "slug": "palm-bridge-investments",
    "companyName": "Palm Bridge Investments",
    "licenseNumber": "BVP-TO-22Q1-EF4V-Z5",
    "issueDate": "2022-01-01",
    "expiryDate": "2027-01-01",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@palm-bridge-investments.cv",
    "contactPhone": "",
    "businessCategory": "Treasury Outsourcing",
    "complianceNotes": "Maintains bilingual client disclosures in Portuguese and English.",
    "description": "Founded in 2022, Palm Bridge Investments operates bespoke FX solutions for renewable energy initiatives throughout Boa Vista.",
    "keyPersons": [
      {
        "name": "Wilma Ramos",
        "role": "Chief Technology Officer"
      },
      {
        "name": "Sergio Esteves",
        "role": "Market Surveillance Officer"
      },
      {
        "name": "Nuno Fernandes",
        "role": "Head of Trading"
      }
    ]
  },
  {
    "id": 10,
    "slug": "sand-bridge-services",
    "companyName": "Sand Bridge Services",
    "licenseNumber": "BVP-CR-23Q2-967U-WP",
    "issueDate": "2023-04-08",
    "expiryDate": "2028-04-08",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@sand-bridge-services.cv",
    "contactPhone": "",
    "businessCategory": "Corporate FX Risk Advisory",
    "complianceNotes": "Operates under conditional approval pending technology platform migration.",
    "description": "Founded in 2023, Sand Bridge Services maintains correspondent networks facilitating cross-border commodity trades.",
    "keyPersons": [
      {
        "name": "Igor Macedo",
        "role": "Head of Trading"
      },
      {
        "name": "Helena Silva",
        "role": "Settlement Supervisor"
      },
      {
        "name": "Helena Zamora",
        "role": "Head of Trading"
      },
      {
        "name": "Helena Silva",
        "role": "Market Surveillance Officer"
      }
    ]
  },
  {
    "id": 11,
    "slug": "atlantic-capital-advisors",
    "companyName": "Atlantic Capital Advisors",
    "licenseNumber": "BVP-FX-14Q3-4VAT-Q8",
    "issueDate": "2014-07-15",
    "expiryDate": "2019-07-15",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@atlantic-capital-advisors.cv",
    "contactPhone": "",
    "businessCategory": "Retail FX Brokerage",
    "complianceNotes": "Maintains quarterly compliance updates with the Boa Vista Financial Authority.",
    "description": "Founded in 2014, Atlantic Capital Advisors delivers currency execution and settlement solutions to the Cape Verdean hospitality and tourism sector.",
    "keyPersons": [
      {
        "name": "Teresa Esteves",
        "role": "Market Surveillance Officer"
      },
      {
        "name": "Vasco Henriques",
        "role": "Head of Trading"
      },
      {
        "name": "Ana Quintino",
        "role": "Risk Management Lead"
      },
      {
        "name": "Nuno Quintino",
        "role": "Institutional Liaison"
      }
    ]
  },
  {
    "id": 12,
    "slug": "azure-capital-holdings",
    "companyName": "Azure Capital Holdings",
    "licenseNumber": "BVP-IX-15Q4-XLDS-MP",
    "issueDate": "2015-10-22",
    "expiryDate": "2020-10-22",
    "status": "Under Review",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@azure-capital-holdings.cv",
    "contactPhone": "",
    "businessCategory": "Institutional FX Brokerage",
    "complianceNotes": "Underwent enhanced due diligence during the most recent supervisory cycle.",
    "description": "Founded in 2015, Azure Capital Holdings supports regional exporters with hedging strategies against Euro and USD volatility.",
    "keyPersons": [
      {
        "name": "Fabio Zamora",
        "role": "Client Relations Principal"
      },
      {
        "name": "Igor Xavier",
        "role": "Operations Supervisor"
      },
      {
        "name": "Sergio Henriques",
        "role": "Risk Management Lead"
      },
      {
        "name": "Teresa Neves",
        "role": "Settlement Supervisor"
      }
    ]
  },
  {
    "id": 13,
    "slug": "beacon-capital-partners",
    "companyName": "Beacon Capital Partners",
    "licenseNumber": "BVP-MD-16Q1-SBGR-97",
    "issueDate": "2016-01-01",
    "expiryDate": "2021-01-01",
    "status": "Suspended",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@beacon-capital-partners.cv",
    "contactPhone": "",
    "businessCategory": "Multi-Asset Dealing Desk",
    "complianceNotes": "Submitted revised capital adequacy statement in the last reporting period.",
    "description": "Founded in 2016, Beacon Capital Partners specialises in low-latency order routing for diaspora remittance channels.",
    "keyPersons": [
      {
        "name": "Paulo Quintino",
        "role": "Managing Director"
      },
      {
        "name": "Wilma Neves",
        "role": "Treasury Controller"
      },
      {
        "name": "Luis Almeida",
        "role": "Risk Management Lead"
      },
      {
        "name": "Ana Lima",
        "role": "Managing Director"
      }
    ]
  },
  {
    "id": 14,
    "slug": "blue-capital-ventures",
    "companyName": "Blue Capital Ventures",
    "licenseNumber": "BVP-LP-17Q2-M2KQ-6R",
    "issueDate": "2017-04-08",
    "expiryDate": "2022-04-08",
    "status": "Lapsed",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@blue-capital-ventures.cv",
    "contactPhone": "",
    "businessCategory": "FX Liquidity Provision",
    "complianceNotes": "Implements mandatory client asset segregation with monthly reconciliations.",
    "description": "Founded in 2017, Blue Capital Ventures partners with local banks to provide treasury outsourcing and liquidity management.",
    "keyPersons": [
      {
        "name": "Carla Lima",
        "role": "Treasury Controller"
      },
      {
        "name": "Luis Barbosa",
        "role": "Market Surveillance Officer"
      }
    ]
  },
  {
    "id": 15,
    "slug": "coral-capital-consulting",
    "companyName": "Coral Capital Consulting",
    "licenseNumber": "BVP-CB-18Q3-GRNP-3A",
    "issueDate": "2018-07-15",
    "expiryDate": "N/A",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@coral-capital-consulting.cv",
    "contactPhone": "",
    "businessCategory": "Commodities Brokerage",
    "complianceNotes": "Participates in cross-border information sharing with Lusophone regulators.",
    "description": "Founded in 2018, Coral Capital Consulting offers portfolio diversification tools for high-net-worth investors across West Africa.",
    "keyPersons": [
      {
        "name": "Nuno Delgado",
        "role": "Risk Management Lead"
      },
      {
        "name": "Yuri Quintino",
        "role": "Settlement Supervisor"
      }
    ]
  },
  {
    "id": 16,
    "slug": "emerald-capital-markets",
    "companyName": "Emerald Capital Markets",
    "licenseNumber": "BVP-DA-19Q4-BGRN-YU",
    "issueDate": "2019-10-22",
    "expiryDate": "2024-10-22",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@emerald-capital-markets.cv",
    "contactPhone": "",
    "businessCategory": "Derivatives Advisory",
    "complianceNotes": "Filed updated disaster recovery plan incorporating offshore redundancy.",
    "description": "Founded in 2019, Emerald Capital Markets focuses on sustainable finance instruments linked to island infrastructure projects.",
    "keyPersons": [
      {
        "name": "Ana Xavier",
        "role": "Institutional Liaison"
      },
      {
        "name": "Marta Esteves",
        "role": "Head of Trading"
      }
    ]
  },
  {
    "id": 17,
    "slug": "harbor-capital-trust",
    "companyName": "Harbor Capital Trust",
    "licenseNumber": "BVP-WM-20Q1-67UM-MC",
    "issueDate": "2020-01-01",
    "expiryDate": "2025-01-01",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@harbor-capital-trust.cv",
    "contactPhone": "",
    "businessCategory": "Wealth Management Services",
    "complianceNotes": "Completed independent AML/CTF audit with satisfactory findings.",
    "description": "Founded in 2020, Harbor Capital Trust implements disciplined risk management tailored to maritime shipping clients.",
    "keyPersons": [
      {
        "name": "Joana Quintino",
        "role": "Chief Technology Officer"
      },
      {
        "name": "Bruno Tavares",
        "role": "Operations Supervisor"
      }
    ]
  },
  {
    "id": 18,
    "slug": "mariner-capital-associates",
    "companyName": "Mariner Capital Associates",
    "licenseNumber": "BVP-PR-21Q2-ZWXL-EW",
    "issueDate": "2021-04-08",
    "expiryDate": "2026-04-08",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@mariner-capital-associates.cv",
    "contactPhone": "",
    "businessCategory": "Payment and Remittance Services",
    "complianceNotes": "Subject to annual prudential assessment focusing on liquidity buffers.",
    "description": "Founded in 2021, Mariner Capital Associates provides onboarding support for fintech entrants expanding into Lusophone markets.",
    "keyPersons": [
      {
        "name": "Vasco Lima",
        "role": "Chief Compliance Officer"
      },
      {
        "name": "Nuno Lima",
        "role": "Chief Technology Officer"
      }
    ]
  },
  {
    "id": 19,
    "slug": "palm-capital-investments",
    "companyName": "Palm Capital Investments",
    "licenseNumber": "BVP-TO-22Q3-UM2K-BC",
    "issueDate": "2022-07-15",
    "expiryDate": "2027-07-15",
    "status": "Under Review",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@palm-capital-investments.cv",
    "contactPhone": "",
    "businessCategory": "Treasury Outsourcing",
    "complianceNotes": "Maintains bilingual client disclosures in Portuguese and English.",
    "description": "Founded in 2022, Palm Capital Investments operates bespoke FX solutions for renewable energy initiatives throughout Boa Vista.",
    "keyPersons": [
      {
        "name": "Helena Delgado",
        "role": "Market Surveillance Officer"
      },
      {
        "name": "Carla Zamora",
        "role": "Market Surveillance Officer"
      },
      {
        "name": "Vasco Esteves",
        "role": "Client Relations Principal"
      }
    ]
  },
  {
    "id": 20,
    "slug": "sand-capital-services",
    "companyName": "Sand Capital Services",
    "licenseNumber": "BVP-CR-23Q4-PC5J-8W",
    "issueDate": "2023-10-22",
    "expiryDate": "2028-10-22",
    "status": "Suspended",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@sand-capital-services.cv",
    "contactPhone": "",
    "businessCategory": "Corporate FX Risk Advisory",
    "complianceNotes": "Operates under conditional approval pending technology platform migration.",
    "description": "Founded in 2023, Sand Capital Services maintains correspondent networks facilitating cross-border commodity trades.",
    "keyPersons": [
      {
        "name": "Sergio Xavier",
        "role": "Operations Supervisor"
      },
      {
        "name": "Paulo Oliveira",
        "role": "Settlement Supervisor"
      },
      {
        "name": "Olivia Xavier",
        "role": "Client Relations Principal"
      }
    ]
  },
  {
    "id": 21,
    "slug": "atlantic-channel-advisors",
    "companyName": "Atlantic Channel Advisors",
    "licenseNumber": "BVP-FX-14Q1-J38H-VE",
    "issueDate": "2014-01-01",
    "expiryDate": "2019-01-01",
    "status": "Lapsed",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@atlantic-channel-advisors.cv",
    "contactPhone": "",
    "businessCategory": "Retail FX Brokerage",
    "complianceNotes": "Maintains quarterly compliance updates with the Boa Vista Financial Authority.",
    "description": "Founded in 2014, Atlantic Channel Advisors delivers currency execution and settlement solutions to the Cape Verdean hospitality and tourism sector.",
    "keyPersons": [
      {
        "name": "Daniel Quintino",
        "role": "Settlement Supervisor"
      },
      {
        "name": "Daniel Cardoso",
        "role": "Head of Trading"
      },
      {
        "name": "Helena Pereira",
        "role": "Client Relations Principal"
      }
    ]
  },
  {
    "id": 22,
    "slug": "azure-channel-holdings",
    "companyName": "Azure Channel Holdings",
    "licenseNumber": "BVP-IX-15Q2-DSBG-SY",
    "issueDate": "2015-04-08",
    "expiryDate": "N/A",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@azure-channel-holdings.cv",
    "contactPhone": "",
    "businessCategory": "Institutional FX Brokerage",
    "complianceNotes": "Underwent enhanced due diligence during the most recent supervisory cycle.",
    "description": "Founded in 2015, Azure Channel Holdings supports regional exporters with hedging strategies against Euro and USD volatility.",
    "keyPersons": [
      {
        "name": "Olivia Lima",
        "role": "Treasury Controller"
      },
      {
        "name": "Rita Ramos",
        "role": "Operations Supervisor"
      },
      {
        "name": "Bruno Gomes",
        "role": "Chief Technology Officer"
      }
    ]
  },
  {
    "id": 23,
    "slug": "beacon-channel-partners",
    "companyName": "Beacon Channel Partners",
    "licenseNumber": "BVP-MD-16Q3-8HEF-PH",
    "issueDate": "2016-07-15",
    "expiryDate": "2021-07-15",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@beacon-channel-partners.cv",
    "contactPhone": "",
    "businessCategory": "Multi-Asset Dealing Desk",
    "complianceNotes": "Submitted revised capital adequacy statement in the last reporting period.",
    "description": "Founded in 2016, Beacon Channel Partners specialises in low-latency order routing for diaspora remittance channels.",
    "keyPersons": [
      {
        "name": "Bruno Delgado",
        "role": "Head of Trading"
      },
      {
        "name": "Fabio Fernandes",
        "role": "Chief Technology Officer"
      },
      {
        "name": "Sergio Almeida",
        "role": "Chief Technology Officer"
      }
    ]
  },
  {
    "id": 24,
    "slug": "blue-channel-ventures",
    "companyName": "Blue Channel Ventures",
    "licenseNumber": "BVP-LP-17Q4-38HE-G3",
    "issueDate": "2017-10-22",
    "expiryDate": "2022-10-22",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@blue-channel-ventures.cv",
    "contactPhone": "",
    "businessCategory": "FX Liquidity Provision",
    "complianceNotes": "Implements mandatory client asset segregation with monthly reconciliations.",
    "description": "Founded in 2017, Blue Channel Ventures partners with local banks to provide treasury outsourcing and liquidity management.",
    "keyPersons": [
      {
        "name": "Marta Xavier",
        "role": "Institutional Liaison"
      },
      {
        "name": "Sergio Vidal",
        "role": "Market Surveillance Officer"
      },
      {
        "name": "Marta Ramos",
        "role": "Chief Technology Officer"
      },
      {
        "name": "Olivia Barbosa",
        "role": "Institutional Liaison"
      }
    ]
  },
  {
    "id": 25,
    "slug": "coral-channel-consulting",
    "companyName": "Coral Channel Consulting",
    "licenseNumber": "BVP-CB-18Q1-WXLD-8K",
    "issueDate": "2018-01-01",
    "expiryDate": "2023-01-01",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@coral-channel-consulting.cv",
    "contactPhone": "",
    "businessCategory": "Commodities Brokerage",
    "complianceNotes": "Participates in cross-border information sharing with Lusophone regulators.",
    "description": "Founded in 2018, Coral Channel Consulting offers portfolio diversification tools for high-net-worth investors across West Africa.",
    "keyPersons": [
      {
        "name": "Wilma Quintino",
        "role": "Client Relations Principal"
      },
      {
        "name": "Helena Macedo",
        "role": "Settlement Supervisor"
      },
      {
        "name": "Fabio Lima",
        "role": "Treasury Controller"
      },
      {
        "name": "Teresa Zamora",
        "role": "Settlement Supervisor"
      }
    ]
  },
  {
    "id": 26,
    "slug": "emerald-channel-markets",
    "companyName": "Emerald Channel Markets",
    "licenseNumber": "BVP-DA-19Q2-RNPC-25",
    "issueDate": "2019-04-08",
    "expiryDate": "2024-04-08",
    "status": "Under Review",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@emerald-channel-markets.cv",
    "contactPhone": "",
    "businessCategory": "Derivatives Advisory",
    "complianceNotes": "Filed updated disaster recovery plan incorporating offshore redundancy.",
    "description": "Founded in 2019, Emerald Channel Markets focuses on sustainable finance instruments linked to island infrastructure projects.",
    "keyPersons": [
      {
        "name": "Igor Henriques",
        "role": "Chief Compliance Officer"
      },
      {
        "name": "Teresa Almeida",
        "role": "Head of Trading"
      },
      {
        "name": "Yuri Barbosa",
        "role": "Treasury Controller"
      },
      {
        "name": "Bruno Tavares",
        "role": "Managing Director"
      }
    ]
  },
  {
    "id": 27,
    "slug": "harbor-channel-trust",
    "companyName": "Harbor Channel Trust",
    "licenseNumber": "BVP-WM-20Q3-LDSB-XK",
    "issueDate": "2020-07-15",
    "expiryDate": "2025-07-15",
    "status": "Suspended",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@harbor-channel-trust.cv",
    "contactPhone": "",
    "businessCategory": "Wealth Management Services",
    "complianceNotes": "Completed independent AML/CTF audit with satisfactory findings.",
    "description": "Founded in 2020, Harbor Channel Trust implements disciplined risk management tailored to maritime shipping clients.",
    "keyPersons": [
      {
        "name": "Teresa Cardoso",
        "role": "AML Programme Lead"
      },
      {
        "name": "Igor Pereira",
        "role": "Operations Supervisor"
      },
      {
        "name": "Rita Silva",
        "role": "Treasury Controller"
      },
      {
        "name": "Helena Ramos",
        "role": "Chief Compliance Officer"
      }
    ]
  },
  {
    "id": 28,
    "slug": "mariner-channel-associates",
    "companyName": "Mariner Channel Associates",
    "licenseNumber": "BVP-PR-21Q4-F4VA-U5",
    "issueDate": "2021-10-22",
    "expiryDate": "2026-10-22",
    "status": "Lapsed",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@mariner-channel-associates.cv",
    "contactPhone": "",
    "businessCategory": "Payment and Remittance Services",
    "complianceNotes": "Subject to annual prudential assessment focusing on liquidity buffers.",
    "description": "Founded in 2021, Mariner Channel Associates provides onboarding support for fintech entrants expanding into Lusophone markets.",
    "keyPersons": [
      {
        "name": "Fabio Vidal",
        "role": "Risk Management Lead"
      },
      {
        "name": "Wilma Delgado",
        "role": "Chief Technology Officer"
      }
    ]
  },
  {
    "id": 29,
    "slug": "palm-channel-investments",
    "companyName": "Palm Channel Investments",
    "licenseNumber": "BVP-TO-22Q1-ATY9-GN",
    "issueDate": "2022-01-01",
    "expiryDate": "N/A",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@palm-channel-investments.cv",
    "contactPhone": "",
    "businessCategory": "Treasury Outsourcing",
    "complianceNotes": "Maintains bilingual client disclosures in Portuguese and English.",
    "description": "Founded in 2022, Palm Channel Investments operates bespoke FX solutions for renewable energy initiatives throughout Boa Vista.",
    "keyPersons": [
      {
        "name": "Paulo Pereira",
        "role": "Settlement Supervisor"
      },
      {
        "name": "Joana Silva",
        "role": "Market Surveillance Officer"
      }
    ]
  },
  {
    "id": 30,
    "slug": "sand-channel-services",
    "companyName": "Sand Channel Services",
    "licenseNumber": "BVP-CR-23Q2-5J38-D7",
    "issueDate": "2023-04-08",
    "expiryDate": "2028-04-08",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@sand-channel-services.cv",
    "contactPhone": "",
    "businessCategory": "Corporate FX Risk Advisory",
    "complianceNotes": "Operates under conditional approval pending technology platform migration.",
    "description": "Founded in 2023, Sand Channel Services maintains correspondent networks facilitating cross-border commodity trades.",
    "keyPersons": [
      {
        "name": "Carla Henriques",
        "role": "Chief Technology Officer"
      },
      {
        "name": "Yuri Gomes",
        "role": "Settlement Supervisor"
      }
    ]
  },
  {
    "id": 31,
    "slug": "atlantic-coast-advisors",
    "companyName": "Atlantic Coast Advisors",
    "licenseNumber": "BVP-FX-14Q3-Y967-AR",
    "issueDate": "2014-07-15",
    "expiryDate": "2019-07-15",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@atlantic-coast-advisors.cv",
    "contactPhone": "",
    "businessCategory": "Retail FX Brokerage",
    "complianceNotes": "Maintains quarterly compliance updates with the Boa Vista Financial Authority.",
    "description": "Founded in 2014, Atlantic Coast Advisors delivers currency execution and settlement solutions to the Cape Verdean hospitality and tourism sector.",
    "keyPersons": [
      {
        "name": "Nuno Cardoso",
        "role": "Head of Trading"
      },
      {
        "name": "Marta Xavier",
        "role": "Chief Compliance Officer"
      }
    ]
  },
  {
    "id": 32,
    "slug": "azure-coast-holdings",
    "companyName": "Azure Coast Holdings",
    "licenseNumber": "BVP-IX-15Q4-TY96-4A",
    "issueDate": "2015-10-22",
    "expiryDate": "2020-10-22",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@azure-coast-holdings.cv",
    "contactPhone": "",
    "businessCategory": "Institutional FX Brokerage",
    "complianceNotes": "Underwent enhanced due diligence during the most recent supervisory cycle.",
    "description": "Founded in 2015, Azure Coast Holdings supports regional exporters with hedging strategies against Euro and USD volatility.",
    "keyPersons": [
      {
        "name": "Ana Vidal",
        "role": "Market Surveillance Officer"
      },
      {
        "name": "Ana Macedo",
        "role": "Operations Supervisor"
      }
    ]
  },
  {
    "id": 33,
    "slug": "beacon-coast-partners",
    "companyName": "Beacon Coast Partners",
    "licenseNumber": "BVP-MD-16Q1-NPC5-RT",
    "issueDate": "2016-01-01",
    "expiryDate": "2021-01-01",
    "status": "Under Review",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@beacon-coast-partners.cv",
    "contactPhone": "",
    "businessCategory": "Multi-Asset Dealing Desk",
    "complianceNotes": "Submitted revised capital adequacy statement in the last reporting period.",
    "description": "Founded in 2016, Beacon Coast Partners specialises in low-latency order routing for diaspora remittance channels.",
    "keyPersons": [
      {
        "name": "Joana Pereira",
        "role": "Client Relations Principal"
      },
      {
        "name": "Nuno Barbosa",
        "role": "Chief Technology Officer"
      },
      {
        "name": "Bruno Zamora",
        "role": "Market Surveillance Officer"
      }
    ]
  },
  {
    "id": 34,
    "slug": "blue-coast-ventures",
    "companyName": "Blue Coast Ventures",
    "licenseNumber": "BVP-LP-17Q2-HEF4-NC",
    "issueDate": "2017-04-08",
    "expiryDate": "2022-04-08",
    "status": "Suspended",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@blue-coast-ventures.cv",
    "contactPhone": "",
    "businessCategory": "FX Liquidity Provision",
    "complianceNotes": "Implements mandatory client asset segregation with monthly reconciliations.",
    "description": "Founded in 2017, Blue Coast Ventures partners with local banks to provide treasury outsourcing and liquidity management.",
    "keyPersons": [
      {
        "name": "Vasco Henriques",
        "role": "Managing Director"
      },
      {
        "name": "Carla Quintino",
        "role": "Market Surveillance Officer"
      },
      {
        "name": "Teresa Quintino",
        "role": "Market Surveillance Officer"
      }
    ]
  },
  {
    "id": 35,
    "slug": "coral-coast-consulting",
    "companyName": "Coral Coast Consulting",
    "licenseNumber": "BVP-CB-18Q3-C5J3-JT",
    "issueDate": "2018-07-15",
    "expiryDate": "2023-07-15",
    "status": "Lapsed",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@coral-coast-consulting.cv",
    "contactPhone": "",
    "businessCategory": "Commodities Brokerage",
    "complianceNotes": "Participates in cross-border information sharing with Lusophone regulators.",
    "description": "Founded in 2018, Coral Coast Consulting offers portfolio diversification tools for high-net-worth investors across West Africa.",
    "keyPersons": [
      {
        "name": "Helena Cardoso",
        "role": "Treasury Controller"
      },
      {
        "name": "Olivia Esteves",
        "role": "Settlement Supervisor"
      },
      {
        "name": "Nuno Henriques",
        "role": "Market Surveillance Officer"
      }
    ]
  },
  {
    "id": 36,
    "slug": "emerald-coast-markets",
    "companyName": "Emerald Coast Markets",
    "licenseNumber": "BVP-DA-19Q4-7UM2-FC",
    "issueDate": "2019-10-22",
    "expiryDate": "N/A",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@emerald-coast-markets.cv",
    "contactPhone": "",
    "businessCategory": "Derivatives Advisory",
    "complianceNotes": "Filed updated disaster recovery plan incorporating offshore redundancy.",
    "description": "Founded in 2019, Emerald Coast Markets focuses on sustainable finance instruments linked to island infrastructure projects.",
    "keyPersons": [
      {
        "name": "Sergio Vidal",
        "role": "Risk Management Lead"
      },
      {
        "name": "Daniel Tavares",
        "role": "Chief Compliance Officer"
      },
      {
        "name": "Fabio Barbosa",
        "role": "Institutional Liaison"
      }
    ]
  },
  {
    "id": 37,
    "slug": "harbor-coast-trust",
    "companyName": "Harbor Coast Trust",
    "licenseNumber": "BVP-WM-20Q1-2KQZ-4V",
    "issueDate": "2020-01-01",
    "expiryDate": "2025-01-01",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@harbor-coast-trust.cv",
    "contactPhone": "",
    "businessCategory": "Wealth Management Services",
    "complianceNotes": "Completed independent AML/CTF audit with satisfactory findings.",
    "description": "Founded in 2020, Harbor Coast Trust implements disciplined risk management tailored to maritime shipping clients.",
    "keyPersons": [
      {
        "name": "Daniel Pereira",
        "role": "Institutional Liaison"
      },
      {
        "name": "Rita Henriques",
        "role": "Operations Supervisor"
      },
      {
        "name": "Ana Silva",
        "role": "Institutional Liaison"
      }
    ]
  },
  {
    "id": 38,
    "slug": "mariner-coast-associates",
    "companyName": "Mariner Coast Associates",
    "licenseNumber": "BVP-PR-21Q2-VATY-ZE",
    "issueDate": "2021-04-08",
    "expiryDate": "2026-04-08",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@mariner-coast-associates.cv",
    "contactPhone": "",
    "businessCategory": "Payment and Remittance Services",
    "complianceNotes": "Subject to annual prudential assessment focusing on liquidity buffers.",
    "description": "Founded in 2021, Mariner Coast Associates provides onboarding support for fintech entrants expanding into Lusophone markets.",
    "keyPersons": [
      {
        "name": "Olivia Henriques",
        "role": "Chief Technology Officer"
      },
      {
        "name": "Elisa Zamora",
        "role": "Chief Technology Officer"
      },
      {
        "name": "Rita Macedo",
        "role": "Institutional Liaison"
      },
      {
        "name": "Vasco Henriques",
        "role": "Settlement Supervisor"
      }
    ]
  },
  {
    "id": 39,
    "slug": "palm-coast-investments",
    "companyName": "Palm Coast Investments",
    "licenseNumber": "BVP-TO-22Q3-QZWX-TY",
    "issueDate": "2022-07-15",
    "expiryDate": "2027-07-15",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@palm-coast-investments.cv",
    "contactPhone": "",
    "businessCategory": "Treasury Outsourcing",
    "complianceNotes": "Maintains bilingual client disclosures in Portuguese and English.",
    "description": "Founded in 2022, Palm Coast Investments operates bespoke FX solutions for renewable energy initiatives throughout Boa Vista.",
    "keyPersons": [
      {
        "name": "Bruno Barbosa",
        "role": "Chief Compliance Officer"
      },
      {
        "name": "Sergio Neves",
        "role": "Market Surveillance Officer"
      },
      {
        "name": "Luis Cardoso",
        "role": "Settlement Supervisor"
      },
      {
        "name": "Carla Fernandes",
        "role": "Managing Director"
      }
    ]
  },
  {
    "id": 40,
    "slug": "sand-coast-services",
    "companyName": "Sand Coast Services",
    "licenseNumber": "BVP-CR-23Q4-KQZW-QH",
    "issueDate": "2023-10-22",
    "expiryDate": "2028-10-22",
    "status": "Under Review",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@sand-coast-services.cv",
    "contactPhone": "",
    "businessCategory": "Corporate FX Risk Advisory",
    "complianceNotes": "Operates under conditional approval pending technology platform migration.",
    "description": "Founded in 2023, Sand Coast Services maintains correspondent networks facilitating cross-border commodity trades.",
    "keyPersons": [
      {
        "name": "Marta Tavares",
        "role": "Market Surveillance Officer"
      },
      {
        "name": "Helena Cardoso",
        "role": "Settlement Supervisor"
      },
      {
        "name": "Elisa Tavares",
        "role": "Settlement Supervisor"
      },
      {
        "name": "Helena Cardoso",
        "role": "Chief Compliance Officer"
      }
    ]
  },
  {
    "id": 41,
    "slug": "atlantic-crest-advisors",
    "companyName": "Atlantic Crest Advisors",
    "licenseNumber": "BVP-FX-14Q1-EF4V-C2",
    "issueDate": "2014-01-01",
    "expiryDate": "2019-01-01",
    "status": "Suspended",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@atlantic-crest-advisors.cv",
    "contactPhone": "",
    "businessCategory": "Retail FX Brokerage",
    "complianceNotes": "Maintains quarterly compliance updates with the Boa Vista Financial Authority.",
    "description": "Founded in 2014, Atlantic Crest Advisors delivers currency execution and settlement solutions to the Cape Verdean hospitality and tourism sector.",
    "keyPersons": [
      {
        "name": "Wilma Oliveira",
        "role": "Operations Supervisor"
      },
      {
        "name": "Teresa Quintino",
        "role": "Chief Compliance Officer"
      },
      {
        "name": "Wilma Neves",
        "role": "Settlement Supervisor"
      },
      {
        "name": "Nuno Almeida",
        "role": "Head of Trading"
      }
    ]
  },
  {
    "id": 42,
    "slug": "azure-crest-holdings",
    "companyName": "Azure Crest Holdings",
    "licenseNumber": "BVP-IX-15Q2-967U-9G",
    "issueDate": "2015-04-08",
    "expiryDate": "2020-04-08",
    "status": "Lapsed",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@azure-crest-holdings.cv",
    "contactPhone": "",
    "businessCategory": "Institutional FX Brokerage",
    "complianceNotes": "Underwent enhanced due diligence during the most recent supervisory cycle.",
    "description": "Founded in 2015, Azure Crest Holdings supports regional exporters with hedging strategies against Euro and USD volatility.",
    "keyPersons": [
      {
        "name": "Igor Gomes",
        "role": "Settlement Supervisor"
      },
      {
        "name": "Igor Fernandes",
        "role": "Operations Supervisor"
      }
    ]
  },
  {
    "id": 43,
    "slug": "beacon-crest-partners",
    "companyName": "Beacon Crest Partners",
    "licenseNumber": "BVP-MD-16Q3-4VAT-62",
    "issueDate": "2016-07-15",
    "expiryDate": "N/A",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@beacon-crest-partners.cv",
    "contactPhone": "",
    "businessCategory": "Multi-Asset Dealing Desk",
    "complianceNotes": "Submitted revised capital adequacy statement in the last reporting period.",
    "description": "Founded in 2016, Beacon Crest Partners specialises in low-latency order routing for diaspora remittance channels.",
    "keyPersons": [
      {
        "name": "Teresa Barbosa",
        "role": "Treasury Controller"
      },
      {
        "name": "Wilma Vidal",
        "role": "Chief Technology Officer"
      }
    ]
  },
  {
    "id": 44,
    "slug": "blue-crest-ventures",
    "companyName": "Blue Crest Ventures",
    "licenseNumber": "BVP-LP-17Q4-XLDS-3K",
    "issueDate": "2017-10-22",
    "expiryDate": "2022-10-22",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@blue-crest-ventures.cv",
    "contactPhone": "",
    "businessCategory": "FX Liquidity Provision",
    "complianceNotes": "Implements mandatory client asset segregation with monthly reconciliations.",
    "description": "Founded in 2017, Blue Crest Ventures partners with local banks to provide treasury outsourcing and liquidity management.",
    "keyPersons": [
      {
        "name": "Fabio Tavares",
        "role": "Head of Trading"
      },
      {
        "name": "Joana Lima",
        "role": "Market Surveillance Officer"
      }
    ]
  },
  {
    "id": 45,
    "slug": "coral-crest-consulting",
    "companyName": "Coral Crest Consulting",
    "licenseNumber": "BVP-CB-18Q1-SBGR-Q4",
    "issueDate": "2018-01-01",
    "expiryDate": "2023-01-01",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@coral-crest-consulting.cv",
    "contactPhone": "",
    "businessCategory": "Commodities Brokerage",
    "complianceNotes": "Participates in cross-border information sharing with Lusophone regulators.",
    "description": "Founded in 2018, Coral Crest Consulting offers portfolio diversification tools for high-net-worth investors across West Africa.",
    "keyPersons": [
      {
        "name": "Paulo Oliveira",
        "role": "Institutional Liaison"
      },
      {
        "name": "Yuri Almeida",
        "role": "Settlement Supervisor"
      }
    ]
  },
  {
    "id": 46,
    "slug": "emerald-crest-markets",
    "companyName": "Emerald Crest Markets",
    "licenseNumber": "BVP-DA-19Q2-M2KQ-HN",
    "issueDate": "2019-04-08",
    "expiryDate": "2024-04-08",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@emerald-crest-markets.cv",
    "contactPhone": "",
    "businessCategory": "Derivatives Advisory",
    "complianceNotes": "Filed updated disaster recovery plan incorporating offshore redundancy.",
    "description": "Founded in 2019, Emerald Crest Markets focuses on sustainable finance instruments linked to island infrastructure projects.",
    "keyPersons": [
      {
        "name": "Carla Gomes",
        "role": "Client Relations Principal"
      },
      {
        "name": "Marta Oliveira",
        "role": "Chief Compliance Officer"
      }
    ]
  },
  {
    "id": 47,
    "slug": "harbor-crest-trust",
    "companyName": "Harbor Crest Trust",
    "licenseNumber": "BVP-WM-20Q3-GRNP-E7",
    "issueDate": "2020-07-15",
    "expiryDate": "2025-07-15",
    "status": "Under Review",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@harbor-crest-trust.cv",
    "contactPhone": "",
    "businessCategory": "Wealth Management Services",
    "complianceNotes": "Completed independent AML/CTF audit with satisfactory findings.",
    "description": "Founded in 2020, Harbor Crest Trust implements disciplined risk management tailored to maritime shipping clients.",
    "keyPersons": [
      {
        "name": "Nuno Barbosa",
        "role": "Managing Director"
      },
      {
        "name": "Ana Delgado",
        "role": "Operations Supervisor"
      },
      {
        "name": "Helena Ramos",
        "role": "Chief Compliance Officer"
      }
    ]
  },
  {
    "id": 48,
    "slug": "mariner-crest-associates",
    "companyName": "Mariner Crest Associates",
    "licenseNumber": "BVP-PR-21Q4-BGRN-BR",
    "issueDate": "2021-10-22",
    "expiryDate": "2026-10-22",
    "status": "Suspended",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@mariner-crest-associates.cv",
    "contactPhone": "",
    "businessCategory": "Payment and Remittance Services",
    "complianceNotes": "Subject to annual prudential assessment focusing on liquidity buffers.",
    "description": "Founded in 2021, Mariner Crest Associates provides onboarding support for fintech entrants expanding into Lusophone markets.",
    "keyPersons": [
      {
        "name": "Ana Tavares",
        "role": "AML Programme Lead"
      },
      {
        "name": "Nuno Ramos",
        "role": "Chief Technology Officer"
      },
      {
        "name": "Ana Lima",
        "role": "Chief Compliance Officer"
      }
    ]
  },
  {
    "id": 49,
    "slug": "palm-crest-investments",
    "companyName": "Palm Crest Investments",
    "licenseNumber": "BVP-TO-22Q1-67UM-Y9",
    "issueDate": "2022-01-01",
    "expiryDate": "2027-01-01",
    "status": "Lapsed",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@palm-crest-investments.cv",
    "contactPhone": "",
    "businessCategory": "Treasury Outsourcing",
    "complianceNotes": "Maintains bilingual client disclosures in Portuguese and English.",
    "description": "Founded in 2022, Palm Crest Investments operates bespoke FX solutions for renewable energy initiatives throughout Boa Vista.",
    "keyPersons": [
      {
        "name": "Joana Oliveira",
        "role": "Risk Management Lead"
      },
      {
        "name": "Bruno Gomes",
        "role": "AML Programme Lead"
      },
      {
        "name": "Sergio Cardoso",
        "role": "Chief Compliance Officer"
      }
    ]
  },
  {
    "id": 50,
    "slug": "sand-crest-services",
    "companyName": "Sand Crest Services",
    "licenseNumber": "BVP-CR-23Q2-ZWXL-VQ",
    "issueDate": "2023-04-08",
    "expiryDate": "N/A",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@sand-crest-services.cv",
    "contactPhone": "",
    "businessCategory": "Corporate FX Risk Advisory",
    "complianceNotes": "Operates under conditional approval pending technology platform migration.",
    "description": "Founded in 2023, Sand Crest Services maintains correspondent networks facilitating cross-border commodity trades.",
    "keyPersons": [
      {
        "name": "Vasco Gomes",
        "role": "Settlement Supervisor"
      },
      {
        "name": "Olivia Xavier",
        "role": "Settlement Supervisor"
      },
      {
        "name": "Marta Tavares",
        "role": "Head of Trading"
      }
    ]
  },
  {
    "id": 51,
    "slug": "atlantic-harbor-advisors",
    "companyName": "Atlantic Harbor Advisors",
    "licenseNumber": "BVP-FX-14Q3-UM2K-S9",
    "issueDate": "2014-07-15",
    "expiryDate": "2019-07-15",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@atlantic-harbor-advisors.cv",
    "contactPhone": "",
    "businessCategory": "Retail FX Brokerage",
    "complianceNotes": "Maintains quarterly compliance updates with the Boa Vista Financial Authority.",
    "description": "Founded in 2014, Atlantic Harbor Advisors delivers currency execution and settlement solutions to the Cape Verdean hospitality and tourism sector.",
    "keyPersons": [
      {
        "name": "Helena Barbosa",
        "role": "Chief Technology Officer"
      },
      {
        "name": "Daniel Macedo",
        "role": "Chief Compliance Officer"
      },
      {
        "name": "Elisa Neves",
        "role": "Head of Trading"
      },
      {
        "name": "Wilma Silva",
        "role": "Managing Director"
      }
    ]
  },
  {
    "id": 52,
    "slug": "azure-harbor-holdings",
    "companyName": "Azure Harbor Holdings",
    "licenseNumber": "BVP-IX-15Q4-PC5J-KT",
    "issueDate": "2015-10-22",
    "expiryDate": "2020-10-22",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@azure-harbor-holdings.cv",
    "contactPhone": "",
    "businessCategory": "Institutional FX Brokerage",
    "complianceNotes": "Underwent enhanced due diligence during the most recent supervisory cycle.",
    "description": "Founded in 2015, Azure Harbor Holdings supports regional exporters with hedging strategies against Euro and USD volatility.",
    "keyPersons": [
      {
        "name": "Sergio Silva",
        "role": "Head of Trading"
      },
      {
        "name": "Paulo Barbosa",
        "role": "Operations Supervisor"
      },
      {
        "name": "Yuri Delgado",
        "role": "Head of Trading"
      },
      {
        "name": "Carla Quintino",
        "role": "Chief Compliance Officer"
      }
    ]
  },
  {
    "id": 53,
    "slug": "beacon-harbor-partners",
    "companyName": "Beacon Harbor Partners",
    "licenseNumber": "BVP-MD-16Q1-J38H-BB",
    "issueDate": "2016-01-01",
    "expiryDate": "2021-01-01",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@beacon-harbor-partners.cv",
    "contactPhone": "",
    "businessCategory": "Multi-Asset Dealing Desk",
    "complianceNotes": "Submitted revised capital adequacy statement in the last reporting period.",
    "description": "Founded in 2016, Beacon Harbor Partners specialises in low-latency order routing for diaspora remittance channels.",
    "keyPersons": [
      {
        "name": "Daniel Neves",
        "role": "Market Surveillance Officer"
      },
      {
        "name": "Elisa Pereira",
        "role": "Chief Technology Officer"
      },
      {
        "name": "Paulo Vidal",
        "role": "Risk Management Lead"
      },
      {
        "name": "Igor Neves",
        "role": "Head of Trading"
      }
    ]
  },
  {
    "id": 54,
    "slug": "blue-harbor-ventures",
    "companyName": "Blue Harbor Ventures",
    "licenseNumber": "BVP-LP-17Q2-DSBG-5V",
    "issueDate": "2017-04-08",
    "expiryDate": "2022-04-08",
    "status": "Under Review",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@blue-harbor-ventures.cv",
    "contactPhone": "",
    "businessCategory": "FX Liquidity Provision",
    "complianceNotes": "Implements mandatory client asset segregation with monthly reconciliations.",
    "description": "Founded in 2017, Blue Harbor Ventures partners with local banks to provide treasury outsourcing and liquidity management.",
    "keyPersons": [
      {
        "name": "Olivia Fernandes",
        "role": "Operations Supervisor"
      },
      {
        "name": "Sergio Esteves",
        "role": "AML Programme Lead"
      },
      {
        "name": "Joana Oliveira",
        "role": "Risk Management Lead"
      },
      {
        "name": "Olivia Lima",
        "role": "Head of Trading"
      }
    ]
  },
  {
    "id": 55,
    "slug": "coral-harbor-consulting",
    "companyName": "Coral Harbor Consulting",
    "licenseNumber": "BVP-CB-18Q3-8HEF-2E",
    "issueDate": "2018-07-15",
    "expiryDate": "2023-07-15",
    "status": "Suspended",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@coral-harbor-consulting.cv",
    "contactPhone": "",
    "businessCategory": "Commodities Brokerage",
    "complianceNotes": "Participates in cross-border information sharing with Lusophone regulators.",
    "description": "Founded in 2018, Coral Harbor Consulting offers portfolio diversification tools for high-net-worth investors across West Africa.",
    "keyPersons": [
      {
        "name": "Bruno Almeida",
        "role": "Managing Director"
      },
      {
        "name": "Fabio Silva",
        "role": "Settlement Supervisor"
      },
      {
        "name": "Daniel Fernandes",
        "role": "Risk Management Lead"
      },
      {
        "name": "Teresa Gomes",
        "role": "Risk Management Lead"
      }
    ]
  },
  {
    "id": 56,
    "slug": "emerald-harbor-markets",
    "companyName": "Emerald Harbor Markets",
    "licenseNumber": "BVP-DA-19Q4-38HE-XY",
    "issueDate": "2019-10-22",
    "expiryDate": "2024-10-22",
    "status": "Lapsed",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@emerald-harbor-markets.cv",
    "contactPhone": "",
    "businessCategory": "Derivatives Advisory",
    "complianceNotes": "Filed updated disaster recovery plan incorporating offshore redundancy.",
    "description": "Founded in 2019, Emerald Harbor Markets focuses on sustainable finance instruments linked to island infrastructure projects.",
    "keyPersons": [
      {
        "name": "Marta Silva",
        "role": "Treasury Controller"
      },
      {
        "name": "Teresa Henriques",
        "role": "Chief Compliance Officer"
      }
    ]
  },
  {
    "id": 57,
    "slug": "harbor-harbor-trust",
    "companyName": "Harbor Harbor Trust",
    "licenseNumber": "BVP-WM-20Q1-WXLD-KD",
    "issueDate": "2020-01-01",
    "expiryDate": "N/A",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@harbor-harbor-trust.cv",
    "contactPhone": "",
    "businessCategory": "Wealth Management Services",
    "complianceNotes": "Completed independent AML/CTF audit with satisfactory findings.",
    "description": "Founded in 2020, Harbor Harbor Trust implements disciplined risk management tailored to maritime shipping clients.",
    "keyPersons": [
      {
        "name": "Wilma Neves",
        "role": "Risk Management Lead"
      },
      {
        "name": "Igor Xavier",
        "role": "Operations Supervisor"
      }
    ]
  },
  {
    "id": 58,
    "slug": "mariner-harbor-associates",
    "companyName": "Mariner Harbor Associates",
    "licenseNumber": "BVP-PR-21Q2-RNPC-GX",
    "issueDate": "2021-04-08",
    "expiryDate": "2026-04-08",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@mariner-harbor-associates.cv",
    "contactPhone": "",
    "businessCategory": "Payment and Remittance Services",
    "complianceNotes": "Subject to annual prudential assessment focusing on liquidity buffers.",
    "description": "Founded in 2021, Mariner Harbor Associates provides onboarding support for fintech entrants expanding into Lusophone markets.",
    "keyPersons": [
      {
        "name": "Igor Fernandes",
        "role": "Institutional Liaison"
      },
      {
        "name": "Vasco Neves",
        "role": "Chief Technology Officer"
      }
    ]
  },
  {
    "id": 59,
    "slug": "palm-harbor-investments",
    "companyName": "Palm Harbor Investments",
    "licenseNumber": "BVP-TO-22Q3-LDSB-AG",
    "issueDate": "2022-07-15",
    "expiryDate": "2027-07-15",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@palm-harbor-investments.cv",
    "contactPhone": "",
    "businessCategory": "Treasury Outsourcing",
    "complianceNotes": "Maintains bilingual client disclosures in Portuguese and English.",
    "description": "Founded in 2022, Palm Harbor Investments operates bespoke FX solutions for renewable energy initiatives throughout Boa Vista.",
    "keyPersons": [
      {
        "name": "Teresa Almeida",
        "role": "Chief Technology Officer"
      },
      {
        "name": "Joana Cardoso",
        "role": "AML Programme Lead"
      }
    ]
  },
  {
    "id": 60,
    "slug": "sand-harbor-services",
    "companyName": "Sand Harbor Services",
    "licenseNumber": "BVP-CR-23Q4-F4VA-72",
    "issueDate": "2023-10-22",
    "expiryDate": "2028-10-22",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@sand-harbor-services.cv",
    "contactPhone": "",
    "businessCategory": "Corporate FX Risk Advisory",
    "complianceNotes": "Operates under conditional approval pending technology platform migration.",
    "description": "Founded in 2023, Sand Harbor Services maintains correspondent networks facilitating cross-border commodity trades.",
    "keyPersons": [
      {
        "name": "Fabio Silva",
        "role": "Chief Compliance Officer"
      },
      {
        "name": "Yuri Quintino",
        "role": "Settlement Supervisor"
      }
    ]
  },
  {
    "id": 61,
    "slug": "atlantic-horizon-advisors",
    "companyName": "Atlantic Horizon Advisors",
    "licenseNumber": "BVP-FX-14Q1-ATY9-UJ",
    "issueDate": "2014-01-01",
    "expiryDate": "2019-01-01",
    "status": "Under Review",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@atlantic-horizon-advisors.cv",
    "contactPhone": "",
    "businessCategory": "Retail FX Brokerage",
    "complianceNotes": "Maintains quarterly compliance updates with the Boa Vista Financial Authority.",
    "description": "Founded in 2014, Atlantic Horizon Advisors delivers currency execution and settlement solutions to the Cape Verdean hospitality and tourism sector.",
    "keyPersons": [
      {
        "name": "Paulo Neves",
        "role": "AML Programme Lead"
      },
      {
        "name": "Luis Fernandes",
        "role": "Chief Compliance Officer"
      },
      {
        "name": "Marta Macedo",
        "role": "Client Relations Principal"
      }
    ]
  },
  {
    "id": 62,
    "slug": "azure-horizon-holdings",
    "companyName": "Azure Horizon Holdings",
    "licenseNumber": "BVP-IX-15Q2-5J38-R4",
    "issueDate": "2015-04-08",
    "expiryDate": "2020-04-08",
    "status": "Suspended",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@azure-horizon-holdings.cv",
    "contactPhone": "",
    "businessCategory": "Institutional FX Brokerage",
    "complianceNotes": "Underwent enhanced due diligence during the most recent supervisory cycle.",
    "description": "Founded in 2015, Azure Horizon Holdings supports regional exporters with hedging strategies against Euro and USD volatility.",
    "keyPersons": [
      {
        "name": "Carla Fernandes",
        "role": "Operations Supervisor"
      },
      {
        "name": "Ana Tavares",
        "role": "Risk Management Lead"
      },
      {
        "name": "Fabio Delgado",
        "role": "Client Relations Principal"
      }
    ]
  },
  {
    "id": 63,
    "slug": "beacon-horizon-partners",
    "companyName": "Beacon Horizon Partners",
    "licenseNumber": "BVP-MD-16Q3-Y967-NN",
    "issueDate": "2016-07-15",
    "expiryDate": "2021-07-15",
    "status": "Lapsed",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@beacon-horizon-partners.cv",
    "contactPhone": "",
    "businessCategory": "Multi-Asset Dealing Desk",
    "complianceNotes": "Submitted revised capital adequacy statement in the last reporting period.",
    "description": "Founded in 2016, Beacon Horizon Partners specialises in low-latency order routing for diaspora remittance channels.",
    "keyPersons": [
      {
        "name": "Nuno Almeida",
        "role": "Settlement Supervisor"
      },
      {
        "name": "Nuno Lima",
        "role": "Chief Technology Officer"
      },
      {
        "name": "Yuri Vidal",
        "role": "Client Relations Principal"
      }
    ]
  },
  {
    "id": 64,
    "slug": "blue-horizon-ventures",
    "companyName": "Blue Horizon Ventures",
    "licenseNumber": "BVP-LP-17Q4-TY96-J7",
    "issueDate": "2017-10-22",
    "expiryDate": "N/A",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@blue-horizon-ventures.cv",
    "contactPhone": "",
    "businessCategory": "FX Liquidity Provision",
    "complianceNotes": "Implements mandatory client asset segregation with monthly reconciliations.",
    "description": "Founded in 2017, Blue Horizon Ventures partners with local banks to provide treasury outsourcing and liquidity management.",
    "keyPersons": [
      {
        "name": "Ana Silva",
        "role": "Treasury Controller"
      },
      {
        "name": "Bruno Zamora",
        "role": "AML Programme Lead"
      },
      {
        "name": "Rita Neves",
        "role": "Chief Technology Officer"
      }
    ]
  },
  {
    "id": 65,
    "slug": "coral-horizon-consulting",
    "companyName": "Coral Horizon Consulting",
    "licenseNumber": "BVP-CB-18Q1-NPC5-7M",
    "issueDate": "2018-01-01",
    "expiryDate": "2023-01-01",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@coral-horizon-consulting.cv",
    "contactPhone": "",
    "businessCategory": "Commodities Brokerage",
    "complianceNotes": "Participates in cross-border information sharing with Lusophone regulators.",
    "description": "Founded in 2018, Coral Horizon Consulting offers portfolio diversification tools for high-net-worth investors across West Africa.",
    "keyPersons": [
      {
        "name": "Joana Macedo",
        "role": "Head of Trading"
      },
      {
        "name": "Olivia Oliveira",
        "role": "Settlement Supervisor"
      },
      {
        "name": "Luis Esteves",
        "role": "Chief Technology Officer"
      },
      {
        "name": "Daniel Barbosa",
        "role": "Chief Compliance Officer"
      }
    ]
  },
  {
    "id": 66,
    "slug": "emerald-horizon-markets",
    "companyName": "Emerald Horizon Markets",
    "licenseNumber": "BVP-DA-19Q2-HEF4-46",
    "issueDate": "2019-04-08",
    "expiryDate": "2024-04-08",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@emerald-horizon-markets.cv",
    "contactPhone": "",
    "businessCategory": "Derivatives Advisory",
    "complianceNotes": "Filed updated disaster recovery plan incorporating offshore redundancy.",
    "description": "Founded in 2019, Emerald Horizon Markets focuses on sustainable finance instruments linked to island infrastructure projects.",
    "keyPersons": [
      {
        "name": "Vasco Esteves",
        "role": "Institutional Liaison"
      },
      {
        "name": "Daniel Delgado",
        "role": "Chief Compliance Officer"
      },
      {
        "name": "Daniel Xavier",
        "role": "Chief Technology Officer"
      },
      {
        "name": "Joana Zamora",
        "role": "Head of Trading"
      }
    ]
  },
  {
    "id": 67,
    "slug": "harbor-horizon-trust",
    "companyName": "Harbor Horizon Trust",
    "licenseNumber": "BVP-WM-20Q3-C5J3-WQ",
    "issueDate": "2020-07-15",
    "expiryDate": "2025-07-15",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@harbor-horizon-trust.cv",
    "contactPhone": "",
    "businessCategory": "Wealth Management Services",
    "complianceNotes": "Completed independent AML/CTF audit with satisfactory findings.",
    "description": "Founded in 2020, Harbor Horizon Trust implements disciplined risk management tailored to maritime shipping clients.",
    "keyPersons": [
      {
        "name": "Helena Zamora",
        "role": "Client Relations Principal"
      },
      {
        "name": "Paulo Ramos",
        "role": "Risk Management Lead"
      },
      {
        "name": "Wilma Pereira",
        "role": "Treasury Controller"
      },
      {
        "name": "Paulo Tavares",
        "role": "Risk Management Lead"
      }
    ]
  },
  {
    "id": 68,
    "slug": "mariner-horizon-associates",
    "companyName": "Mariner Horizon Associates",
    "licenseNumber": "BVP-PR-21Q4-7UM2-T9",
    "issueDate": "2021-10-22",
    "expiryDate": "2026-10-22",
    "status": "Under Review",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@mariner-horizon-associates.cv",
    "contactPhone": "",
    "businessCategory": "Payment and Remittance Services",
    "complianceNotes": "Subject to annual prudential assessment focusing on liquidity buffers.",
    "description": "Founded in 2021, Mariner Horizon Associates provides onboarding support for fintech entrants expanding into Lusophone markets.",
    "keyPersons": [
      {
        "name": "Sergio Ramos",
        "role": "Managing Director"
      },
      {
        "name": "Elisa Gomes",
        "role": "Chief Technology Officer"
      },
      {
        "name": "Paulo Gomes",
        "role": "Treasury Controller"
      },
      {
        "name": "Vasco Ramos",
        "role": "Operations Supervisor"
      }
    ]
  },
  {
    "id": 69,
    "slug": "palm-horizon-investments",
    "companyName": "Palm Horizon Investments",
    "licenseNumber": "BVP-TO-22Q1-2KQZ-FS",
    "issueDate": "2022-01-01",
    "expiryDate": "2027-01-01",
    "status": "Suspended",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@palm-horizon-investments.cv",
    "contactPhone": "",
    "businessCategory": "Treasury Outsourcing",
    "complianceNotes": "Maintains bilingual client disclosures in Portuguese and English.",
    "description": "Founded in 2022, Palm Horizon Investments operates bespoke FX solutions for renewable energy initiatives throughout Boa Vista.",
    "keyPersons": [
      {
        "name": "Daniel Macedo",
        "role": "AML Programme Lead"
      },
      {
        "name": "Sergio Vidal",
        "role": "AML Programme Lead"
      },
      {
        "name": "Igor Almeida",
        "role": "Treasury Controller"
      },
      {
        "name": "Carla Oliveira",
        "role": "Client Relations Principal"
      }
    ]
  },
  {
    "id": 70,
    "slug": "sand-horizon-services",
    "companyName": "Sand Horizon Services",
    "licenseNumber": "BVP-CR-23Q2-VATY-CB",
    "issueDate": "2023-04-08",
    "expiryDate": "2028-04-08",
    "status": "Lapsed",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@sand-horizon-services.cv",
    "contactPhone": "",
    "businessCategory": "Corporate FX Risk Advisory",
    "complianceNotes": "Operates under conditional approval pending technology platform migration.",
    "description": "Founded in 2023, Sand Horizon Services maintains correspondent networks facilitating cross-border commodity trades.",
    "keyPersons": [
      {
        "name": "Olivia Esteves",
        "role": "Risk Management Lead"
      },
      {
        "name": "Fabio Macedo",
        "role": "Settlement Supervisor"
      }
    ]
  },
  {
    "id": 71,
    "slug": "atlantic-ledger-advisors",
    "companyName": "Atlantic Ledger Advisors",
    "licenseNumber": "BVP-FX-14Q3-QZWX-9V",
    "issueDate": "2014-07-15",
    "expiryDate": "N/A",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@atlantic-ledger-advisors.cv",
    "contactPhone": "",
    "businessCategory": "Retail FX Brokerage",
    "complianceNotes": "Maintains quarterly compliance updates with the Boa Vista Financial Authority.",
    "description": "Founded in 2014, Atlantic Ledger Advisors delivers currency execution and settlement solutions to the Cape Verdean hospitality and tourism sector.",
    "keyPersons": [
      {
        "name": "Bruno Zamora",
        "role": "Settlement Supervisor"
      },
      {
        "name": "Teresa Almeida",
        "role": "Chief Compliance Officer"
      }
    ]
  },
  {
    "id": 72,
    "slug": "azure-ledger-holdings",
    "companyName": "Azure Ledger Holdings",
    "licenseNumber": "BVP-IX-15Q4-KQZW-6B",
    "issueDate": "2015-10-22",
    "expiryDate": "2020-10-22",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@azure-ledger-holdings.cv",
    "contactPhone": "",
    "businessCategory": "Institutional FX Brokerage",
    "complianceNotes": "Underwent enhanced due diligence during the most recent supervisory cycle.",
    "description": "Founded in 2015, Azure Ledger Holdings supports regional exporters with hedging strategies against Euro and USD volatility.",
    "keyPersons": [
      {
        "name": "Marta Ramos",
        "role": "Chief Technology Officer"
      },
      {
        "name": "Helena Pereira",
        "role": "Risk Management Lead"
      }
    ]
  },
  {
    "id": 73,
    "slug": "beacon-ledger-partners",
    "companyName": "Beacon Ledger Partners",
    "licenseNumber": "BVP-MD-16Q1-EF4V-TU",
    "issueDate": "2016-01-01",
    "expiryDate": "2021-01-01",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@beacon-ledger-partners.cv",
    "contactPhone": "",
    "businessCategory": "Multi-Asset Dealing Desk",
    "complianceNotes": "Submitted revised capital adequacy statement in the last reporting period.",
    "description": "Founded in 2016, Beacon Ledger Partners specialises in low-latency order routing for diaspora remittance channels.",
    "keyPersons": [
      {
        "name": "Wilma Macedo",
        "role": "Head of Trading"
      },
      {
        "name": "Vasco Delgado",
        "role": "Chief Technology Officer"
      }
    ]
  },
  {
    "id": 74,
    "slug": "blue-ledger-ventures",
    "companyName": "Blue Ledger Ventures",
    "licenseNumber": "BVP-LP-17Q2-967U-MD",
    "issueDate": "2017-04-08",
    "expiryDate": "2022-04-08",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@blue-ledger-ventures.cv",
    "contactPhone": "",
    "businessCategory": "FX Liquidity Provision",
    "complianceNotes": "Implements mandatory client asset segregation with monthly reconciliations.",
    "description": "Founded in 2017, Blue Ledger Ventures partners with local banks to provide treasury outsourcing and liquidity management.",
    "keyPersons": [
      {
        "name": "Igor Esteves",
        "role": "Market Surveillance Officer"
      },
      {
        "name": "Joana Silva",
        "role": "AML Programme Lead"
      }
    ]
  },
  {
    "id": 75,
    "slug": "coral-ledger-consulting",
    "companyName": "Coral Ledger Consulting",
    "licenseNumber": "BVP-CB-18Q3-4VAT-HX",
    "issueDate": "2018-07-15",
    "expiryDate": "2023-07-15",
    "status": "Under Review",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@coral-ledger-consulting.cv",
    "contactPhone": "",
    "businessCategory": "Commodities Brokerage",
    "complianceNotes": "Participates in cross-border information sharing with Lusophone regulators.",
    "description": "Founded in 2018, Coral Ledger Consulting offers portfolio diversification tools for high-net-worth investors across West Africa.",
    "keyPersons": [
      {
        "name": "Teresa Zamora",
        "role": "Operations Supervisor"
      },
      {
        "name": "Wilma Henriques",
        "role": "Settlement Supervisor"
      },
      {
        "name": "Sergio Esteves",
        "role": "Market Surveillance Officer"
      }
    ]
  },
  {
    "id": 76,
    "slug": "emerald-ledger-markets",
    "companyName": "Emerald Ledger Markets",
    "licenseNumber": "BVP-DA-19Q4-XLDS-EG",
    "issueDate": "2019-10-22",
    "expiryDate": "2024-10-22",
    "status": "Suspended",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@emerald-ledger-markets.cv",
    "contactPhone": "",
    "businessCategory": "Derivatives Advisory",
    "complianceNotes": "Filed updated disaster recovery plan incorporating offshore redundancy.",
    "description": "Founded in 2019, Emerald Ledger Markets focuses on sustainable finance instruments linked to island infrastructure projects.",
    "keyPersons": [
      {
        "name": "Fabio Ramos",
        "role": "Managing Director"
      },
      {
        "name": "Luis Xavier",
        "role": "Chief Compliance Officer"
      },
      {
        "name": "Luis Xavier",
        "role": "Market Surveillance Officer"
      }
    ]
  },
  {
    "id": 77,
    "slug": "harbor-ledger-trust",
    "companyName": "Harbor Ledger Trust",
    "licenseNumber": "BVP-WM-20Q1-SBGR-3Z",
    "issueDate": "2020-01-01",
    "expiryDate": "2025-01-01",
    "status": "Lapsed",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@harbor-ledger-trust.cv",
    "contactPhone": "",
    "businessCategory": "Wealth Management Services",
    "complianceNotes": "Completed independent AML/CTF audit with satisfactory findings.",
    "description": "Founded in 2020, Harbor Ledger Trust implements disciplined risk management tailored to maritime shipping clients.",
    "keyPersons": [
      {
        "name": "Paulo Lima",
        "role": "Treasury Controller"
      },
      {
        "name": "Ana Neves",
        "role": "Risk Management Lead"
      },
      {
        "name": "Elisa Oliveira",
        "role": "Market Surveillance Officer"
      }
    ]
  },
  {
    "id": 78,
    "slug": "mariner-ledger-associates",
    "companyName": "Mariner Ledger Associates",
    "licenseNumber": "BVP-PR-21Q2-M2KQ-YJ",
    "issueDate": "2021-04-08",
    "expiryDate": "N/A",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@mariner-ledger-associates.cv",
    "contactPhone": "",
    "businessCategory": "Payment and Remittance Services",
    "complianceNotes": "Subject to annual prudential assessment focusing on liquidity buffers.",
    "description": "Founded in 2021, Mariner Ledger Associates provides onboarding support for fintech entrants expanding into Lusophone markets.",
    "keyPersons": [
      {
        "name": "Carla Delgado",
        "role": "Risk Management Lead"
      },
      {
        "name": "Marta Barbosa",
        "role": "Chief Technology Officer"
      },
      {
        "name": "Yuri Fernandes",
        "role": "Institutional Liaison"
      }
    ]
  },
  {
    "id": 79,
    "slug": "palm-ledger-investments",
    "companyName": "Palm Ledger Investments",
    "licenseNumber": "BVP-TO-22Q3-GRNP-V4",
    "issueDate": "2022-07-15",
    "expiryDate": "2027-07-15",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@palm-ledger-investments.cv",
    "contactPhone": "",
    "businessCategory": "Treasury Outsourcing",
    "complianceNotes": "Maintains bilingual client disclosures in Portuguese and English.",
    "description": "Founded in 2022, Palm Ledger Investments operates bespoke FX solutions for renewable energy initiatives throughout Boa Vista.",
    "keyPersons": [
      {
        "name": "Nuno Xavier",
        "role": "Institutional Liaison"
      },
      {
        "name": "Bruno Quintino",
        "role": "AML Programme Lead"
      },
      {
        "name": "Paulo Zamora",
        "role": "Institutional Liaison"
      },
      {
        "name": "Luis Henriques",
        "role": "Head of Trading"
      }
    ]
  },
  {
    "id": 80,
    "slug": "sand-ledger-services",
    "companyName": "Sand Ledger Services",
    "licenseNumber": "BVP-CR-23Q4-BGRN-PJ",
    "issueDate": "2023-10-22",
    "expiryDate": "2028-10-22",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@sand-ledger-services.cv",
    "contactPhone": "",
    "businessCategory": "Corporate FX Risk Advisory",
    "complianceNotes": "Operates under conditional approval pending technology platform migration.",
    "description": "Founded in 2023, Sand Ledger Services maintains correspondent networks facilitating cross-border commodity trades.",
    "keyPersons": [
      {
        "name": "Ana Quintino",
        "role": "Chief Technology Officer"
      },
      {
        "name": "Olivia Esteves",
        "role": "Institutional Liaison"
      },
      {
        "name": "Joana Quintino",
        "role": "Institutional Liaison"
      },
      {
        "name": "Paulo Fernandes",
        "role": "Risk Management Lead"
      }
    ]
  },
  {
    "id": 81,
    "slug": "atlantic-maritime-advisors",
    "companyName": "Atlantic Maritime Advisors",
    "licenseNumber": "BVP-FX-14Q1-67UM-B3",
    "issueDate": "2014-01-01",
    "expiryDate": "2019-01-01",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@atlantic-maritime-advisors.cv",
    "contactPhone": "",
    "businessCategory": "Retail FX Brokerage",
    "complianceNotes": "Maintains quarterly compliance updates with the Boa Vista Financial Authority.",
    "description": "Founded in 2014, Atlantic Maritime Advisors delivers currency execution and settlement solutions to the Cape Verdean hospitality and tourism sector.",
    "keyPersons": [
      {
        "name": "Luis Lima",
        "role": "Chief Compliance Officer"
      },
      {
        "name": "Carla Tavares",
        "role": "Chief Compliance Officer"
      },
      {
        "name": "Carla Henriques",
        "role": "Institutional Liaison"
      },
      {
        "name": "Wilma Cardoso",
        "role": "Operations Supervisor"
      }
    ]
  },
  {
    "id": 82,
    "slug": "azure-maritime-holdings",
    "companyName": "Azure Maritime Holdings",
    "licenseNumber": "BVP-IX-15Q2-ZWXL-8M",
    "issueDate": "2015-04-08",
    "expiryDate": "2020-04-08",
    "status": "Under Review",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@azure-maritime-holdings.cv",
    "contactPhone": "",
    "businessCategory": "Institutional FX Brokerage",
    "complianceNotes": "Underwent enhanced due diligence during the most recent supervisory cycle.",
    "description": "Founded in 2015, Azure Maritime Holdings supports regional exporters with hedging strategies against Euro and USD volatility.",
    "keyPersons": [
      {
        "name": "Vasco Delgado",
        "role": "AML Programme Lead"
      },
      {
        "name": "Paulo Henriques",
        "role": "Risk Management Lead"
      },
      {
        "name": "Vasco Barbosa",
        "role": "Settlement Supervisor"
      },
      {
        "name": "Daniel Almeida",
        "role": "Client Relations Principal"
      }
    ]
  },
  {
    "id": 83,
    "slug": "beacon-maritime-partners",
    "companyName": "Beacon Maritime Partners",
    "licenseNumber": "BVP-MD-16Q3-UM2K-56",
    "issueDate": "2016-07-15",
    "expiryDate": "2021-07-15",
    "status": "Suspended",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@beacon-maritime-partners.cv",
    "contactPhone": "",
    "businessCategory": "Multi-Asset Dealing Desk",
    "complianceNotes": "Submitted revised capital adequacy statement in the last reporting period.",
    "description": "Founded in 2016, Beacon Maritime Partners specialises in low-latency order routing for diaspora remittance channels.",
    "keyPersons": [
      {
        "name": "Helena Xavier",
        "role": "Operations Supervisor"
      },
      {
        "name": "Elisa Zamora",
        "role": "Chief Technology Officer"
      },
      {
        "name": "Olivia Silva",
        "role": "Settlement Supervisor"
      },
      {
        "name": "Igor Vidal",
        "role": "Chief Technology Officer"
      }
    ]
  },
  {
    "id": 84,
    "slug": "blue-maritime-ventures",
    "companyName": "Blue Maritime Ventures",
    "licenseNumber": "BVP-LP-17Q4-PC5J-2Q",
    "issueDate": "2017-10-22",
    "expiryDate": "2022-10-22",
    "status": "Lapsed",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@blue-maritime-ventures.cv",
    "contactPhone": "",
    "businessCategory": "FX Liquidity Provision",
    "complianceNotes": "Implements mandatory client asset segregation with monthly reconciliations.",
    "description": "Founded in 2017, Blue Maritime Ventures partners with local banks to provide treasury outsourcing and liquidity management.",
    "keyPersons": [
      {
        "name": "Sergio Quintino",
        "role": "Settlement Supervisor"
      },
      {
        "name": "Rita Oliveira",
        "role": "AML Programme Lead"
      }
    ]
  },
  {
    "id": 85,
    "slug": "coral-maritime-consulting",
    "companyName": "Coral Maritime Consulting",
    "licenseNumber": "BVP-CB-18Q1-J38H-P8",
    "issueDate": "2018-01-01",
    "expiryDate": "N/A",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@coral-maritime-consulting.cv",
    "contactPhone": "",
    "businessCategory": "Commodities Brokerage",
    "complianceNotes": "Participates in cross-border information sharing with Lusophone regulators.",
    "description": "Founded in 2018, Coral Maritime Consulting offers portfolio diversification tools for high-net-worth investors across West Africa.",
    "keyPersons": [
      {
        "name": "Elisa Lima",
        "role": "Treasury Controller"
      },
      {
        "name": "Fabio Cardoso",
        "role": "Institutional Liaison"
      }
    ]
  },
  {
    "id": 86,
    "slug": "emerald-maritime-markets",
    "companyName": "Emerald Maritime Markets",
    "licenseNumber": "BVP-DA-19Q2-DSBG-KS",
    "issueDate": "2019-04-08",
    "expiryDate": "2024-04-08",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@emerald-maritime-markets.cv",
    "contactPhone": "",
    "businessCategory": "Derivatives Advisory",
    "complianceNotes": "Filed updated disaster recovery plan incorporating offshore redundancy.",
    "description": "Founded in 2019, Emerald Maritime Markets focuses on sustainable finance instruments linked to island infrastructure projects.",
    "keyPersons": [
      {
        "name": "Olivia Delgado",
        "role": "Head of Trading"
      },
      {
        "name": "Teresa Ramos",
        "role": "Chief Compliance Officer"
      }
    ]
  },
  {
    "id": 87,
    "slug": "harbor-maritime-trust",
    "companyName": "Harbor Maritime Trust",
    "licenseNumber": "BVP-WM-20Q3-8HEF-DB",
    "issueDate": "2020-07-15",
    "expiryDate": "2025-07-15",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@harbor-maritime-trust.cv",
    "contactPhone": "",
    "businessCategory": "Wealth Management Services",
    "complianceNotes": "Completed independent AML/CTF audit with satisfactory findings.",
    "description": "Founded in 2020, Harbor Maritime Trust implements disciplined risk management tailored to maritime shipping clients.",
    "keyPersons": [
      {
        "name": "Bruno Xavier",
        "role": "Market Surveillance Officer"
      },
      {
        "name": "Helena Fernandes",
        "role": "Risk Management Lead"
      }
    ]
  },
  {
    "id": 88,
    "slug": "mariner-maritime-associates",
    "companyName": "Mariner Maritime Associates",
    "licenseNumber": "BVP-PR-21Q4-38HE-AS",
    "issueDate": "2021-10-22",
    "expiryDate": "2026-10-22",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@mariner-maritime-associates.cv",
    "contactPhone": "",
    "businessCategory": "Payment and Remittance Services",
    "complianceNotes": "Subject to annual prudential assessment focusing on liquidity buffers.",
    "description": "Founded in 2021, Mariner Maritime Associates provides onboarding support for fintech entrants expanding into Lusophone markets.",
    "keyPersons": [
      {
        "name": "Marta Quintino",
        "role": "Client Relations Principal"
      },
      {
        "name": "Vasco Vidal",
        "role": "Chief Technology Officer"
      }
    ]
  },
  {
    "id": 89,
    "slug": "palm-maritime-investments",
    "companyName": "Palm Maritime Investments",
    "licenseNumber": "BVP-TO-22Q1-WXLD-XA",
    "issueDate": "2022-01-01",
    "expiryDate": "2027-01-01",
    "status": "Under Review",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@palm-maritime-investments.cv",
    "contactPhone": "",
    "businessCategory": "Treasury Outsourcing",
    "complianceNotes": "Maintains bilingual client disclosures in Portuguese and English.",
    "description": "Founded in 2022, Palm Maritime Investments operates bespoke FX solutions for renewable energy initiatives throughout Boa Vista.",
    "keyPersons": [
      {
        "name": "Yuri Lima",
        "role": "Managing Director"
      },
      {
        "name": "Joana Lima",
        "role": "AML Programme Lead"
      },
      {
        "name": "Yuri Zamora",
        "role": "Chief Compliance Officer"
      }
    ]
  },
  {
    "id": 90,
    "slug": "sand-maritime-services",
    "companyName": "Sand Maritime Services",
    "licenseNumber": "BVP-CR-23Q2-RNPC-UU",
    "issueDate": "2023-04-08",
    "expiryDate": "2028-04-08",
    "status": "Suspended",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@sand-maritime-services.cv",
    "contactPhone": "",
    "businessCategory": "Corporate FX Risk Advisory",
    "complianceNotes": "Operates under conditional approval pending technology platform migration.",
    "description": "Founded in 2023, Sand Maritime Services maintains correspondent networks facilitating cross-border commodity trades.",
    "keyPersons": [
      {
        "name": "Igor Cardoso",
        "role": "AML Programme Lead"
      },
      {
        "name": "Wilma Almeida",
        "role": "Institutional Liaison"
      },
      {
        "name": "Rita Pereira",
        "role": "Chief Compliance Officer"
      }
    ]
  },
  {
    "id": 91,
    "slug": "atlantic-summit-advisors",
    "companyName": "Atlantic Summit Advisors",
    "licenseNumber": "BVP-FX-14Q3-LDSB-RD",
    "issueDate": "2014-07-15",
    "expiryDate": "2019-07-15",
    "status": "Lapsed",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@atlantic-summit-advisors.cv",
    "contactPhone": "",
    "businessCategory": "Retail FX Brokerage",
    "complianceNotes": "Maintains quarterly compliance updates with the Boa Vista Financial Authority.",
    "description": "Founded in 2014, Atlantic Summit Advisors delivers currency execution and settlement solutions to the Cape Verdean hospitality and tourism sector.",
    "keyPersons": [
      {
        "name": "Teresa Vidal",
        "role": "Risk Management Lead"
      },
      {
        "name": "Luis Pereira",
        "role": "Chief Compliance Officer"
      },
      {
        "name": "Joana Gomes",
        "role": "Chief Compliance Officer"
      }
    ]
  },
  {
    "id": 92,
    "slug": "azure-summit-holdings",
    "companyName": "Azure Summit Holdings",
    "licenseNumber": "BVP-IX-15Q4-F4VA-NX",
    "issueDate": "2015-10-22",
    "expiryDate": "N/A",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@azure-summit-holdings.cv",
    "contactPhone": "",
    "businessCategory": "Institutional FX Brokerage",
    "complianceNotes": "Underwent enhanced due diligence during the most recent supervisory cycle.",
    "description": "Founded in 2015, Azure Summit Holdings supports regional exporters with hedging strategies against Euro and USD volatility.",
    "keyPersons": [
      {
        "name": "Fabio Pereira",
        "role": "Settlement Supervisor"
      },
      {
        "name": "Ana Delgado",
        "role": "Risk Management Lead"
      },
      {
        "name": "Daniel Almeida",
        "role": "Head of Trading"
      }
    ]
  },
  {
    "id": 93,
    "slug": "beacon-summit-partners",
    "companyName": "Beacon Summit Partners",
    "licenseNumber": "BVP-MD-16Q1-ATY9-AF",
    "issueDate": "2016-01-01",
    "expiryDate": "2021-01-01",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@beacon-summit-partners.cv",
    "contactPhone": "",
    "businessCategory": "Multi-Asset Dealing Desk",
    "complianceNotes": "Submitted revised capital adequacy statement in the last reporting period.",
    "description": "Founded in 2016, Beacon Summit Partners specialises in low-latency order routing for diaspora remittance channels.",
    "keyPersons": [
      {
        "name": "Rita Henriques",
        "role": "Chief Technology Officer"
      },
      {
        "name": "Marta Silva",
        "role": "Client Relations Principal"
      },
      {
        "name": "Wilma Ramos",
        "role": "Head of Trading"
      },
      {
        "name": "Rita Quintino",
        "role": "Risk Management Lead"
      }
    ]
  },
  {
    "id": 94,
    "slug": "blue-summit-ventures",
    "companyName": "Blue Summit Ventures",
    "licenseNumber": "BVP-LP-17Q2-5J38-7Z",
    "issueDate": "2017-04-08",
    "expiryDate": "2022-04-08",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@blue-summit-ventures.cv",
    "contactPhone": "",
    "businessCategory": "FX Liquidity Provision",
    "complianceNotes": "Implements mandatory client asset segregation with monthly reconciliations.",
    "description": "Founded in 2017, Blue Summit Ventures partners with local banks to provide treasury outsourcing and liquidity management.",
    "keyPersons": [
      {
        "name": "Carla Cardoso",
        "role": "Chief Compliance Officer"
      },
      {
        "name": "Bruno Gomes",
        "role": "AML Programme Lead"
      },
      {
        "name": "Olivia Lima",
        "role": "Head of Trading"
      },
      {
        "name": "Yuri Oliveira",
        "role": "Operations Supervisor"
      }
    ]
  },
  {
    "id": 95,
    "slug": "coral-summit-consulting",
    "companyName": "Coral Summit Consulting",
    "licenseNumber": "BVP-CB-18Q3-Y967-ZF",
    "issueDate": "2018-07-15",
    "expiryDate": "2023-07-15",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@coral-summit-consulting.cv",
    "contactPhone": "",
    "businessCategory": "Commodities Brokerage",
    "complianceNotes": "Participates in cross-border information sharing with Lusophone regulators.",
    "description": "Founded in 2018, Coral Summit Consulting offers portfolio diversification tools for high-net-worth investors across West Africa.",
    "keyPersons": [
      {
        "name": "Nuno Vidal",
        "role": "Market Surveillance Officer"
      },
      {
        "name": "Nuno Xavier",
        "role": "Institutional Liaison"
      },
      {
        "name": "Igor Cardoso",
        "role": "Head of Trading"
      },
      {
        "name": "Daniel Lima",
        "role": "Client Relations Principal"
      }
    ]
  },
  {
    "id": 96,
    "slug": "emerald-summit-markets",
    "companyName": "Emerald Summit Markets",
    "licenseNumber": "BVP-DA-19Q4-TY96-WZ",
    "issueDate": "2019-10-22",
    "expiryDate": "2024-10-22",
    "status": "Under Review",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@emerald-summit-markets.cv",
    "contactPhone": "",
    "businessCategory": "Derivatives Advisory",
    "complianceNotes": "Filed updated disaster recovery plan incorporating offshore redundancy.",
    "description": "Founded in 2019, Emerald Summit Markets focuses on sustainable finance instruments linked to island infrastructure projects.",
    "keyPersons": [
      {
        "name": "Ana Pereira",
        "role": "Operations Supervisor"
      },
      {
        "name": "Carla Macedo",
        "role": "Chief Compliance Officer"
      },
      {
        "name": "Bruno Tavares",
        "role": "Risk Management Lead"
      },
      {
        "name": "Joana Gomes",
        "role": "Chief Technology Officer"
      }
    ]
  },
  {
    "id": 97,
    "slug": "harbor-summit-trust",
    "companyName": "Harbor Summit Trust",
    "licenseNumber": "BVP-WM-20Q1-NPC5-JH",
    "issueDate": "2020-01-01",
    "expiryDate": "2025-01-01",
    "status": "Suspended",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@harbor-summit-trust.cv",
    "contactPhone": "",
    "businessCategory": "Wealth Management Services",
    "complianceNotes": "Completed independent AML/CTF audit with satisfactory findings.",
    "description": "Founded in 2020, Harbor Summit Trust implements disciplined risk management tailored to maritime shipping clients.",
    "keyPersons": [
      {
        "name": "Luis Henriques",
        "role": "Managing Director"
      },
      {
        "name": "Paulo Barbosa",
        "role": "Risk Management Lead"
      },
      {
        "name": "Teresa Neves",
        "role": "Risk Management Lead"
      },
      {
        "name": "Paulo Delgado",
        "role": "Treasury Controller"
      }
    ]
  },
  {
    "id": 98,
    "slug": "mariner-summit-associates",
    "companyName": "Mariner Summit Associates",
    "licenseNumber": "BVP-PR-21Q2-HEF4-F3",
    "issueDate": "2021-04-08",
    "expiryDate": "2026-04-08",
    "status": "Lapsed",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@mariner-summit-associates.cv",
    "contactPhone": "",
    "businessCategory": "Payment and Remittance Services",
    "complianceNotes": "Subject to annual prudential assessment focusing on liquidity buffers.",
    "description": "Founded in 2021, Mariner Summit Associates provides onboarding support for fintech entrants expanding into Lusophone markets.",
    "keyPersons": [
      {
        "name": "Vasco Cardoso",
        "role": "Treasury Controller"
      },
      {
        "name": "Daniel Pereira",
        "role": "Client Relations Principal"
      }
    ]
  },
  {
    "id": 99,
    "slug": "palm-summit-investments",
    "companyName": "Palm Summit Investments",
    "licenseNumber": "BVP-TO-22Q3-C5J3-CM",
    "issueDate": "2022-07-15",
    "expiryDate": "N/A",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@palm-summit-investments.cv",
    "contactPhone": "",
    "businessCategory": "Treasury Outsourcing",
    "complianceNotes": "Maintains bilingual client disclosures in Portuguese and English.",
    "description": "Founded in 2022, Palm Summit Investments operates bespoke FX solutions for renewable energy initiatives throughout Boa Vista.",
    "keyPersons": [
      {
        "name": "Helena Vidal",
        "role": "Risk Management Lead"
      },
      {
        "name": "Rita Esteves",
        "role": "AML Programme Lead"
      }
    ]
  },
  {
    "id": 100,
    "slug": "sand-summit-services",
    "companyName": "Sand Summit Services",
    "licenseNumber": "BVP-CR-23Q4-7UM2-96",
    "issueDate": "2023-10-22",
    "expiryDate": "2028-10-22",
    "status": "Active",
    "registeredAddress": "Boa Vista, Republic of Cabo Verde",
    "contactEmail": "licensing@sand-summit-services.cv",
    "contactPhone": "",
    "businessCategory": "Corporate FX Risk Advisory",
    "complianceNotes": "Operates under conditional approval pending technology platform migration.",
    "description": "Founded in 2023, Sand Summit Services maintains correspondent networks facilitating cross-border commodity trades.",
    "keyPersons": [
      {
        "name": "Sergio Pereira",
        "role": "Institutional Liaison"
      },
      {
        "name": "Fabio Tavares",
        "role": "Institutional Liaison"
      }
    ]
  }
] satisfies LicenseRecord[];

export function getLicenseBySlug(slug: string) {
  return licenses.find((entry) => entry.slug === slug);
}

export function searchLicenses(query: string) {
  const normalized = query.trim().toLowerCase();
  if (!normalized) return licenses;
  return licenses.filter((entry) => {
    return (
      entry.companyName.toLowerCase().includes(normalized) ||
      entry.licenseNumber.toLowerCase().includes(normalized) ||
      entry.businessCategory.toLowerCase().includes(normalized) ||
      entry.description.toLowerCase().includes(normalized)
    );
  });
}
